// AUTO-GENERATED by scripts/generate-pack-registry.mjs. Do not edit by hand.
import { booksWordsPack } from './booksWords';
import { disneyPack } from './disney';
import { foodTravelPack } from './foodTravel';
import { historyGeographyPack } from './historyGeography';
import { moviesTvPack } from './moviesTv';
import { scienceNaturePack } from './scienceNature';
import { sportsGamesPack } from './sportsGames';

export const generatedBuiltInPacks = [booksWordsPack, disneyPack, foodTravelPack, historyGeographyPack, moviesTvPack, scienceNaturePack, sportsGamesPack];
