// AUTO-GENERATED by scripts/generate-pack-registry.mjs. Do not edit by hand.
import { disneyPack } from './disney';
import { moviesTvPack } from './moviesTv';
import { scienceNaturePack } from './scienceNature';

export const generatedBuiltInPacks = [disneyPack, moviesTvPack, scienceNaturePack];
