// Generated by scripts/deal-or-dud/render-narration.ts. Seconds of each tutorial narration clip.
export const NARRATION_SECONDS: Record<string, number> = {
  "tut-1": 5.53,
  "tut-2": 5.29,
  "tut-3": 5.78,
  "tut-4": 5.84,
  "tut-5": 4.69,
  "tut-6": 6.01,
  "tut-7": 7.56
};
