// Generated by scripts/deal-or-dud/render-narration.ts. Seconds of each tutorial narration clip.
export const NARRATION_SECONDS: Record<string, number> = {
  "tut-1": 5.82,
  "tut-2": 9.86,
  "tut-3": 5.36,
  "tut-4": 6.78,
  "tut-5": 6.11,
  "tut-6": 8.74,
  "tut-7": 3.8
};
