// Generated by scripts/deal-or-dud/render-narration.ts. Seconds of each tutorial narration clip.
export const NARRATION_SECONDS: Record<string, number> = {
  "tut-1": 6.22,
  "tut-2": 5.83,
  "tut-3": 3.48,
  "tut-4": 4.22,
  "tut-5": 4.21,
  "tut-6": 7.16
};
