// Copies the Fluent Emoji 3D images (Microsoft, MIT) for every emoji Deal or Dud draws into public/deal-or-dud/art/,
// shrunk to 128px, and writes src/games/deal-or-dud/artManifest.ts so screens only ask for images that exist.
//
//   [FLUENT_EMOJI=<fluentui-emoji/assets folder>] [FFMPEG=<path to ffmpeg>] npx tsx scripts/deal-or-dud/copy-art.ts
//
// An emoji with no 3D image keeps drawing as text.
import { execFileSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { AVATAR_PRESETS } from '../../src/games/deal-or-dud/content/cues';
import { AUDIENCES, MODIFIERS, PRODUCTS } from '../../src/games/deal-or-dud/content/words';
import { CATEGORIES } from '../../src/games/deal-or-dud/content/scorecard';
import { emojiKey } from '../../src/games/deal-or-dud/ui/emojiKey';

const ASSETS = process.env.FLUENT_EMOJI ?? 'C:/Users/caleb/code/tools/fluent-emoji/assets';
const FFMPEG = process.env.FFMPEG ?? 'ffmpeg';
const outDir = resolve('public/deal-or-dud/art');
/** Extra emoji the screens draw outside the content pools (tutorial, peeks, trophy). */
const EXTRA = ['👀', '🤫', '🏆', '🔒', '🍞', '🦜', '👵'];

const wanted = new Set<string>([
  ...AVATAR_PRESETS.flatMap((preset) => [preset.emoji, preset.prop ?? '']),
  ...PRODUCTS.map((item) => item.emoji), ...MODIFIERS.map((item) => item.emoji), ...AUDIENCES.map((item) => item.emoji),
  ...CATEGORIES.map((item) => item.icon), ...EXTRA
].filter(Boolean));

// Index every Fluent folder by its glyph, without variation selectors.
const byKey = new Map<string, string>();
for (const folder of readdirSync(ASSETS)) {
  const meta = join(ASSETS, folder, 'metadata.json');
  if (!existsSync(meta)) continue;
  const glyph = (JSON.parse(readFileSync(meta, 'utf8')) as { glyph?: string }).glyph;
  if (glyph) byKey.set(emojiKey(glyph), join(ASSETS, folder));
}

function image3d(folder: string): string | null {
  for (const dir of [join(folder, '3D'), join(folder, 'Default', '3D')]) {
    if (!existsSync(dir)) continue;
    const png = readdirSync(dir).find((file) => file.endsWith('.png'));
    if (png) return join(dir, png);
  }
  return null;
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(outDir, { recursive: true });
// The images are MIT licensed; their notice ships with them.
copyFileSync(join(ASSETS, '..', 'LICENSE'), join(outDir, 'LICENSE-fluent-emoji.txt'));
const found: string[] = [];
const missing: string[] = [];
for (const emoji of wanted) {
  const key = emojiKey(emoji);
  const folder = byKey.get(key);
  const source = folder && image3d(folder);
  if (!source) { missing.push(emoji); continue; }
  execFileSync(FFMPEG, ['-y', '-loglevel', 'error', '-i', source, '-vf', 'scale=128:128:flags=lanczos', join(outDir, `${key}.png`)]);
  found.push(key);
}
found.sort();
writeFileSync(resolve('src/games/deal-or-dud/artManifest.ts'),
  `// Generated by scripts/deal-or-dud/copy-art.ts. Emoji with a Fluent 3D image in public/deal-or-dud/art/.\nexport const ART_KEYS: ReadonlySet<string> = new Set(${JSON.stringify(found, null, 2)});\n`);
console.log(`${found.length} images; no 3D image for: ${missing.join(' ') || 'none'}`);
