// Records the Deal or Dud host lines with the narrator service (tools/chatterbox/voice_server.py, Chatterbox),
// then encodes MP3 with ffmpeg. Start the service first, then:
//
//   [DEAL_VOICE_URL=http://127.0.0.1:5123] [FFMPEG=<path to ffmpeg>] npx tsx scripts/deal-or-dud/render-narration.ts [--only=tutorial|lines|suspect] [--match=<regex>]
//
// --only=suspect re-records only clips whose length does not fit their text (the model sometimes rambles or cuts off).
//
// Output:
//   public/deal-or-dud/audio/tut-*.mp3 (tutorial, the two hosts take turns) and src/games/deal-or-dud/narrationDurations.ts
//   public/deal-or-dud/audio/voice/<line>-<variant>-<voice>.mp3 (every fixed line in narrationLines.ts, in both voices)
import { execFileSync } from 'node:child_process';
import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { TUTORIAL_STEPS } from '../../src/games/deal-or-dud/tutorialScript';
import { FIXED_LINES, HOST_VOICES, fixedLineFile, type FixedLineId, type HostVoice } from '../../src/games/deal-or-dud/audio/narrationLines';

const FFMPEG = process.env.FFMPEG ?? 'ffmpeg';
const FFPROBE = FFMPEG.replace(/ffmpeg(\.exe)?$/i, (_, exe: string | undefined) => `ffprobe${exe ?? ''}`);
const SERVICE = (process.env.DEAL_VOICE_URL ?? 'http://127.0.0.1:5123').replace(/\/$/, '');
const only = process.argv.find((arg) => arg.startsWith('--only='))?.slice(7);
// --match=<regex> keeps only clips whose output path matches, e.g. --match="voice/build-|tut-2"
const match = process.argv.find((arg) => arg.startsWith('--match='))?.slice(8);

const outDir = resolve('public/deal-or-dud/audio');
const tempDir = resolve('.data/narration-tmp');

interface Clip { text: string; voice: HostVoice; target: string; tutorialId?: string }

const tutorial: Clip[] = TUTORIAL_STEPS.map((step, index) => ({
  text: step.line, voice: HOST_VOICES[index % HOST_VOICES.length], target: join(outDir, `${step.id}.mp3`), tutorialId: step.id
}));
const lines: Clip[] = (Object.entries(FIXED_LINES) as [FixedLineId, readonly string[]][]).flatMap(([id, variants]) =>
  variants.flatMap((text, variant) => HOST_VOICES.map((voice) => ({ text, voice, target: join(outDir, fixedLineFile(id, variant, voice)) }))));

function seconds(file: string): number {
  return Number(execFileSync(FFPROBE, ['-v', 'error', '-show_entries', 'format=duration', '-of', 'csv=p=0', file]).toString().trim());
}

/** Same bounds as the narrator service, plus the silent tail the service adds. */
function fits(clip: Clip): boolean {
  if (!existsSync(clip.target)) return false;
  const words = Math.max(1, clip.text.split(/\s+/).length);
  const spoken = seconds(clip.target) - 0.2;
  return spoken >= 0.16 * words + 0.2 && spoken <= 0.55 * words + 0.8;
}

async function record(clip: Clip): Promise<void> {
  const response = await fetch(`${SERVICE}/speak?voice=${clip.voice}&text=${encodeURIComponent(clip.text)}`);
  if (!response.ok) throw new Error(`Narrator service failed (${response.status}) on: ${clip.text}`);
  const wav = join(tempDir, 'line.wav');
  writeFileSync(wav, new Uint8Array(await response.arrayBuffer()));
  mkdirSync(dirname(clip.target), { recursive: true });
  // Same loudness target for every line so the hosts sit evenly over the music.
  execFileSync(FFMPEG, ['-y', '-loglevel', 'error', '-i', wav, '-af', 'loudnorm=I=-16:TP=-1.5', '-ar', '44100', '-b:a', '128k', clip.target]);
  console.log(clip.target.slice(outDir.length + 1), seconds(clip.target).toFixed(2), 's');
}

const health = await fetch(`${SERVICE}/health`).catch(() => null);
if (!health?.ok) throw new Error(`Start the narrator service first (tools/chatterbox/start-voice.bat); nothing answered at ${SERVICE}`);
mkdirSync(join(outDir, 'voice'), { recursive: true });
mkdirSync(tempDir, { recursive: true });

const picked = only === 'tutorial' ? tutorial : only === 'lines' ? lines : only === 'suspect' ? [...tutorial, ...lines].filter((clip) => !fits(clip)) : [...tutorial, ...lines];
const chosen = match ? picked.filter((clip) => new RegExp(match).test(clip.target.replace(/\\/g, '/'))) : picked;
if (only === 'suspect') console.log(`${chosen.length} clips to redo:`, chosen.map((clip) => clip.target.slice(outDir.length + 1)).join(', ') || 'none');
for (const clip of chosen) await record(clip);

if (chosen.some((clip) => clip.tutorialId)) {
  const durations = Object.fromEntries(tutorial.map((clip) => [clip.tutorialId!, Math.round(seconds(clip.target) * 100) / 100]));
  writeFileSync(resolve('src/games/deal-or-dud/narrationDurations.ts'),
    `// Generated by scripts/deal-or-dud/render-narration.ts. Seconds of each tutorial narration clip.\nexport const NARRATION_SECONDS: Record<string, number> = ${JSON.stringify(durations, null, 2)};\n`);
}
rmSync(tempDir, { recursive: true, force: true });
