// Card-builder pools: a twist, a product, a who and a feature make
// "Cocaine-laced gas station sushi made by Satan, with a built-in bidet".
// Only the product is required, so every product is short, general and funny on its own ("Adult diapers"); the other
// steps are optional and each one still reads right when any of the others is skipped.
// Entries can carry a tone, but every game deals from the whole deck now (GAME_TONE), so the cards leave it out.
// Twists list the product forms they make sense with, so a headline never comes out broken.
import type { ProductForm, Tone } from '../types';

export interface ProductWord {
  id: string;
  /** Plural or mass noun used in the headline, e.g. "toasters". */
  text: string;
  form: ProductForm;
  emoji: string;
  tone?: Tone;
}

export interface ModifierWord {
  id: string;
  /** Goes in front of the product: "haunted toasters". */
  text: string;
  emoji: string;
  forms: readonly ProductForm[];
  tone?: Tone;
}

export interface AudienceWord {
  id: string;
  /** Goes after the connector: "toasters for pirates", "toasters made by pirates". */
  text: string;
  emoji: string;
  tone?: Tone;
}

export interface FeatureWord {
  id: string;
  /**
   * Goes at the end: "toasters for pirates, with a built-in bidet". Always a "with…", "plus…" or "-ed by…" phrase, never
   * "that explodes", so it reads right after any product, singular or plural (a test checks the first word).
   */
  text: string;
  emoji: string;
  tone?: Tone;
}

export type ConnectorId = 'for' | 'made-by' | 'made-from' | 'tested-on' | 'endorsed-by' | 'banned-by' | 'stolen-from' | 'hated-by';

/** The word that joins the product to its who: "toasters [made from] gym bros". The first is the default. */
export const CONNECTORS: readonly { id: ConnectorId; text: string }[] = [
  { id: 'for', text: 'for' },
  { id: 'made-by', text: 'made by' },
  { id: 'made-from', text: 'made from' },
  { id: 'tested-on', text: 'tested on' },
  { id: 'endorsed-by', text: 'endorsed by' },
  { id: 'banned-by', text: 'banned by' },
  { id: 'stolen-from', text: 'stolen from' },
  { id: 'hated-by', text: 'hated by' }
];

const ALL: readonly ProductForm[] = ['food', 'gadget', 'goods', 'pet', 'service', 'rental', 'digital', 'event'];
const STUFF: readonly ProductForm[] = ['food', 'gadget', 'goods', 'pet'];

// The whole deck is deliberately crude and absurd, South Park style: gross, dark, profane. Sexuality and dating jokes
// are fine; sex itself is not (the content test checks for that).
export const PRODUCTS: readonly ProductWord[] = [
  // Food
  { id: 'gas-station-sushi', text: 'gas station sushi', form: 'food', emoji: '🍣' },
  { id: 'hot-dog-water', text: 'hot dog water', form: 'food', emoji: '🌭' },
  { id: 'mystery-meat', text: 'mystery meat', form: 'food', emoji: '🍖' },
  { id: 'roadkill', text: 'roadkill', form: 'food', emoji: '🦨' },
  { id: 'prison-wine', text: 'prison wine', form: 'food', emoji: '🍷' },
  { id: 'bathtub-gin', text: 'bathtub gin', form: 'food', emoji: '🛁' },
  { id: 'expired-milk', text: 'expired milk', form: 'food', emoji: '🥛' },
  { id: 'pre-chewed-gum', text: 'pre-chewed gum', form: 'food', emoji: '🍬' },
  { id: 'toenail-chips', text: 'toenail chips', form: 'food', emoji: '🥔' },
  { id: 'mayo-shots', text: 'mayonnaise shots', form: 'food', emoji: '🫙' },
  { id: 'leftovers', text: "other people's leftovers", form: 'food', emoji: '🥡' },
  { id: 'airplane-food', text: 'airplane food', form: 'food', emoji: '✈️' },
  { id: 'fruitcake', text: 'fruitcake', form: 'food', emoji: '🍰' },
  { id: 'lard', text: 'lard', form: 'food', emoji: '🧈' },
  { id: 'canned-ham', text: 'canned ham', form: 'food', emoji: '🥫' },
  { id: 'hot-pockets', text: 'Hot Pockets', form: 'food', emoji: '🌯' },
  { id: 'jello-shots', text: 'Jell-O shots', form: 'food', emoji: '🍮' },
  { id: 'raw-eggs', text: 'raw eggs', form: 'food', emoji: '🥚' },
  { id: 'moonshine', text: 'moonshine', form: 'food', emoji: '🌙' },
  { id: 'gravy', text: 'gravy', form: 'food', emoji: '🍲' },
  // Gadgets
  { id: 'toasters', text: 'toasters', form: 'gadget', emoji: '🍞' },
  { id: 'flamethrowers', text: 'flamethrowers', form: 'gadget', emoji: '🔥' },
  { id: 'drones', text: 'drones', form: 'gadget', emoji: '🚁' },
  { id: 'lie-detectors', text: 'lie detectors', form: 'gadget', emoji: '🤥' },
  { id: 'tasers', text: 'tasers', form: 'gadget', emoji: '⚡' },
  { id: 'bidets', text: 'bidets', form: 'gadget', emoji: '🚿' },
  { id: 'robot-vacuums', text: 'robot vacuums', form: 'gadget', emoji: '🧹' },
  { id: 'leaf-blowers', text: 'leaf blowers', form: 'gadget', emoji: '🍃' },
  { id: 'baby-monitors', text: 'baby monitors', form: 'gadget', emoji: '👶' },
  { id: 'smart-fridges', text: 'smart fridges', form: 'gadget', emoji: '🧊' },
  { id: 'massage-chairs', text: 'massage chairs', form: 'gadget', emoji: '💺' },
  { id: 'karaoke-machines', text: 'karaoke machines', form: 'gadget', emoji: '🎤' },
  { id: 'fog-machines', text: 'fog machines', form: 'gadget', emoji: '🌫️' },
  { id: 'metal-detectors', text: 'metal detectors', form: 'gadget', emoji: '🧲' },
  { id: 'breathalyzers', text: 'breathalyzers', form: 'gadget', emoji: '🍺' },
  { id: 'hoverboards', text: 'hoverboards', form: 'gadget', emoji: '🛹' },
  { id: 'night-vision-goggles', text: 'night-vision goggles', form: 'gadget', emoji: '🥽' },
  { id: 'fart-machines', text: 'fart machines', form: 'gadget', emoji: '💨' },
  { id: 'jetpacks', text: 'jetpacks', form: 'gadget', emoji: '🚀' },
  { id: 'selfie-sticks', text: 'selfie sticks', form: 'gadget', emoji: '🤳' },
  // Goods
  { id: 'used-toothbrushes', text: 'used toothbrushes', form: 'goods', emoji: '🪥' },
  { id: 'adult-diapers', text: 'adult diapers', form: 'goods', emoji: '🩲' },
  { id: 'urinal-cakes', text: 'urinal cakes', form: 'goods', emoji: '🚽' },
  { id: 'haunted-dolls', text: 'creepy dolls', form: 'goods', emoji: '🪆' },
  { id: 'counterfeit-money', text: 'counterfeit money', form: 'goods', emoji: '💵' },
  { id: 'toilet-paper', text: 'toilet paper', form: 'goods', emoji: '🧻' },
  { id: 'scented-candles', text: 'scented candles', form: 'goods', emoji: '🕯️' },
  { id: 'garden-gnomes', text: 'garden gnomes', form: 'goods', emoji: '🍄' },
  { id: 'fake-mustaches', text: 'fake mustaches', form: 'goods', emoji: '🥸' },
  { id: 'toupees', text: 'toupees', form: 'goods', emoji: '💇' },
  { id: 'dentures', text: 'dentures', form: 'goods', emoji: '🦷' },
  { id: 'clown-shoes', text: 'clown shoes', form: 'goods', emoji: '👞' },
  { id: 'fanny-packs', text: 'fanny packs', form: 'goods', emoji: '👝' },
  { id: 'tin-foil-hats', text: 'tin foil hats', form: 'goods', emoji: '🎩' },
  { id: 'whoopee-cushions', text: 'whoopee cushions', form: 'goods', emoji: '🎈' },
  { id: 'butt-cream', text: 'butt cream', form: 'goods', emoji: '🧴' },
  { id: 'used-mattresses', text: 'used mattresses', form: 'goods', emoji: '🛏️' },
  { id: 'tighty-whities', text: 'tighty-whities', form: 'goods', emoji: '🩳' },
  { id: 'coffins', text: 'coffins', form: 'goods', emoji: '⚰️' },
  { id: 'duct-tape', text: 'duct tape', form: 'goods', emoji: '🩹' },
  { id: 'wet-wipes', text: 'wet wipes', form: 'goods', emoji: '🧽' },
  // Pets
  { id: 'raccoons', text: 'raccoons', form: 'pet', emoji: '🦝' },
  { id: 'pet-rocks', text: 'pet rocks', form: 'pet', emoji: '🪨' },
  { id: 'hamsters', text: 'hamsters', form: 'pet', emoji: '🐹' },
  { id: 'support-alligators', text: 'emotional support alligators', form: 'pet', emoji: '🐊' },
  { id: 'pigeons', text: 'pigeons', form: 'pet', emoji: '🐦' },
  { id: 'possums', text: 'possums', form: 'pet', emoji: '🐀' },
  { id: 'cockroaches', text: 'cockroaches', form: 'pet', emoji: '🪳' },
  { id: 'ferrets', text: 'ferrets', form: 'pet', emoji: '🦦' },
  { id: 'goats', text: 'goats', form: 'pet', emoji: '🐐' },
  { id: 'llamas', text: 'llamas', form: 'pet', emoji: '🦙' },
  { id: 'geese', text: 'geese', form: 'pet', emoji: '🦢' },
  { id: 'feral-hogs', text: 'feral hogs', form: 'pet', emoji: '🐗' },
  { id: 'leeches', text: 'leeches', form: 'pet', emoji: '🪱' },
  { id: 'tarantulas', text: 'tarantulas', form: 'pet', emoji: '🕷️' },
  { id: 'sea-monkeys', text: 'sea monkeys', form: 'pet', emoji: '🦐' },
  { id: 'chimps', text: 'chimpanzees', form: 'pet', emoji: '🐒' },
  { id: 'bees', text: 'bees', form: 'pet', emoji: '🐝' },
  { id: 'goldfish', text: 'goldfish', form: 'pet', emoji: '🐠' },
  { id: 'skunks', text: 'skunks', form: 'pet', emoji: '🦨' },
  { id: 'bears', text: 'bears', form: 'pet', emoji: '🐻' },
  // Services
  { id: 'backyard-dentistry', text: 'backyard dentistry', form: 'service', emoji: '🪛' },
  { id: 'exorcisms', text: 'exorcisms', form: 'service', emoji: '😈' },
  { id: 'tax-evasion-lessons', text: 'tax evasion lessons', form: 'service', emoji: '📚' },
  { id: 'professional-mourners', text: 'professional mourners', form: 'service', emoji: '😭' },
  { id: 'ransom-notes', text: 'ransom notes', form: 'service', emoji: '✉️' },
  { id: 'colonoscopies', text: 'colonoscopies', form: 'service', emoji: '🩺' },
  { id: 'wedgies', text: 'wedgies', form: 'service', emoji: '😣' },
  { id: 'breakup-texts', text: 'breakup texts', form: 'service', emoji: '💔' },
  { id: 'prison-tattoos', text: 'prison tattoos', form: 'service', emoji: '🖋️' },
  { id: 'therapy', text: 'therapy', form: 'service', emoji: '🛋️' },
  { id: 'divorce-lawyers', text: 'divorce lawyers', form: 'service', emoji: '⚖️' },
  { id: 'discount-hitmen', text: 'discount hitmen', form: 'service', emoji: '🔫' },
  { id: 'babysitting', text: 'babysitting', form: 'service', emoji: '🍼' },
  { id: 'life-coaching', text: 'life coaching', form: 'service', emoji: '📣' },
  { id: 'roasts', text: 'roasts', form: 'service', emoji: '🎙️' },
  { id: 'hauntings', text: 'hauntings', form: 'service', emoji: '👻' },
  { id: 'kidnappings', text: 'surprise kidnappings', form: 'service', emoji: '🎁' },
  { id: 'spray-tans', text: 'spray tans', form: 'service', emoji: '🍊' },
  { id: 'doctors-notes', text: "fake doctor's notes", form: 'service', emoji: '📝' },
  // Rentals
  { id: 'grandma-rentals', text: 'grandma rentals', form: 'rental', emoji: '👵' },
  { id: 'alibis', text: 'alibis', form: 'rental', emoji: '🕵️' },
  { id: 'body-doubles', text: 'body doubles', form: 'rental', emoji: '👯' },
  { id: 'army-tanks', text: 'army tanks', form: 'rental', emoji: '🪖' },
  { id: 'porta-potties', text: 'porta-potties', form: 'rental', emoji: '🚻' },
  { id: 'clowns', text: 'clowns', form: 'rental', emoji: '🤡' },
  { id: 'hearses', text: 'hearses', form: 'rental', emoji: '🪦' },
  { id: 'hot-tubs', text: 'hot tubs', form: 'rental', emoji: '♨️' },
  { id: 'bounce-houses', text: 'bounce houses', form: 'rental', emoji: '🏰' },
  { id: 'jail-cells', text: 'jail cells', form: 'rental', emoji: '🔑' },
  { id: 'stretch-limos', text: 'stretch limos', form: 'rental', emoji: '🚘' },
  { id: 'blimps', text: 'blimps', form: 'rental', emoji: '🎈' },
  { id: 'rent-a-dads', text: 'rent-a-dads', form: 'rental', emoji: '👨' },
  { id: 'wingmen', text: 'wingmen', form: 'rental', emoji: '🪽' },
  { id: 'fake-girlfriends', text: 'fake girlfriends', form: 'rental', emoji: '💅' },
  { id: 'bodyguards', text: 'bodyguards', form: 'rental', emoji: '🕶️' },
  { id: 'pallbearers', text: 'pallbearers', form: 'rental', emoji: '🤵' },
  { id: 'shark-tanks', text: 'shark tanks', form: 'rental', emoji: '🦈' },
  // Digital
  { id: 'dating-apps', text: 'dating apps', form: 'digital', emoji: '📲' },
  { id: 'nfts', text: 'NFTs', form: 'digital', emoji: '🖼️' },
  { id: 'meme-coins', text: 'meme coins', form: 'digital', emoji: '🪙' },
  { id: 'podcasts', text: 'podcasts', form: 'digital', emoji: '🎧' },
  { id: 'pyramid-schemes', text: 'pyramid schemes', form: 'digital', emoji: '🔺' },
  { id: 'deepfakes', text: 'deepfakes', form: 'digital', emoji: '🎭' },
  { id: 'fake-reviews', text: 'fake reviews', form: 'digital', emoji: '⭐' },
  { id: 'spam-emails', text: 'spam emails', form: 'digital', emoji: '📧' },
  { id: 'reality-shows', text: 'reality shows', form: 'digital', emoji: '📺' },
  { id: 'ai-therapists', text: 'AI therapists', form: 'digital', emoji: '🤖' },
  { id: 'video-games', text: 'video games', form: 'digital', emoji: '🎮' },
  { id: 'horoscope-apps', text: 'horoscope apps', form: 'digital', emoji: '🔮' },
  { id: 'chain-letters', text: 'chain letters', form: 'digital', emoji: '⛓️' },
  { id: 'robocalls', text: 'robocalls', form: 'digital', emoji: '☎️' },
  { id: 'livestreams', text: 'livestreams', form: 'digital', emoji: '📹' },
  { id: 'audiobooks', text: 'self-help audiobooks', form: 'digital', emoji: '📖' },
  { id: 'conspiracy-blogs', text: 'conspiracy blogs', form: 'digital', emoji: '🛸' },
  { id: 'cat-videos', text: 'cat videos', form: 'digital', emoji: '🐈' },
  // Events
  { id: 'funeral-raves', text: 'funeral raves', form: 'event', emoji: '🪩' },
  { id: 'toddler-mosh-pits', text: 'toddler mosh pits', form: 'event', emoji: '🤘' },
  { id: 'hot-sauce-challenges', text: 'hot sauce challenges', form: 'event', emoji: '🌶️' },
  { id: 'escape-rooms', text: 'escape rooms', form: 'event', emoji: '🔐' },
  { id: 'gender-reveals', text: 'gender reveal parties', form: 'event', emoji: '💣' },
  { id: 'divorce-parties', text: 'divorce parties', form: 'event', emoji: '🪅' },
  { id: 'monster-truck-weddings', text: 'monster truck weddings', form: 'event', emoji: '🛻' },
  { id: 'seances', text: 'séances', form: 'event', emoji: '🔮' },
  { id: 'bar-crawls', text: 'bar crawls', form: 'event', emoji: '🍻' },
  { id: 'food-fights', text: 'food fights', form: 'event', emoji: '🍝' },
  { id: 'cage-fights', text: 'cage fights', form: 'event', emoji: '🥊' },
  { id: 'pie-eating-contests', text: 'pie-eating contests', form: 'event', emoji: '🥧' },
  { id: 'goat-yoga', text: 'goat yoga', form: 'event', emoji: '🧘' },
  { id: 'demolition-derbies', text: 'demolition derbies', form: 'event', emoji: '🚗' },
  { id: 'talent-shows', text: 'talent shows', form: 'event', emoji: '🎪' },
  { id: 'family-reunions', text: 'family reunions', form: 'event', emoji: '🧓' },
  { id: 'timeshare-pitches', text: 'timeshare presentations', form: 'event', emoji: '🏖️' },
  { id: 'cult-meetings', text: 'cult meetings', form: 'event', emoji: '🕯️' },
  { id: 'interventions', text: 'surprise interventions', form: 'event', emoji: '🎉' },
  // Food, more (2026-09-27)
  { id: 'pickle-juice', text: 'pickle juice', form: 'food', emoji: '🥒' },
  { id: 'gas-station-burritos', text: 'gas station burritos', form: 'food', emoji: '🌯' },
  { id: 'pickled-eggs', text: 'pickled eggs', form: 'food', emoji: '🥚' },
  { id: 'beef-jerky', text: 'beef jerky', form: 'food', emoji: '🥩' },
  { id: 'cafeteria-pizza', text: 'cafeteria pizza', form: 'food', emoji: '🍕' },
  { id: 'cough-syrup', text: 'cough syrup', form: 'food', emoji: '🧪' },
  { id: 'energy-drinks', text: 'energy drinks', form: 'food', emoji: '🥤' },
  { id: 'boxed-wine', text: 'boxed wine', form: 'food', emoji: '🍷' },
  { id: 'cat-food', text: 'cat food', form: 'food', emoji: '🐟' },
  { id: 'dumpster-pizza', text: 'dumpster pizza', form: 'food', emoji: '🗑️' },
  { id: 'ghost-peppers', text: 'ghost peppers', form: 'food', emoji: '🌶️' },
  { id: 'hospital-jell-o', text: 'hospital Jell-O', form: 'food', emoji: '🏥' },
  { id: 'protein-powder', text: 'protein powder', form: 'food', emoji: '💪' },
  { id: 'fermented-shark', text: 'fermented shark', form: 'food', emoji: '🦈' },
  { id: 'deviled-eggs', text: 'deviled eggs', form: 'food', emoji: '😈' },
  { id: 'mystery-casserole', text: 'mystery casserole', form: 'food', emoji: '🥘' },
  { id: 'raw-chicken', text: 'raw chicken', form: 'food', emoji: '🍗' },
  { id: 'fried-butter', text: 'fried butter', form: 'food', emoji: '🧈' },
  { id: 'ranch-dressing', text: 'ranch dressing', form: 'food', emoji: '🥗' },
  { id: 'bone-broth', text: 'bone broth', form: 'food', emoji: '🦴' },
  // Gadgets, more (2026-09-27)
  { id: 'car-alarms', text: 'car alarms', form: 'gadget', emoji: '🚨' },
  { id: 'tanning-beds', text: 'tanning beds', form: 'gadget', emoji: '☀️' },
  { id: 'lava-lamps', text: 'lava lamps', form: 'gadget', emoji: '🌋' },
  { id: 'electric-chairs', text: 'electric chairs', form: 'gadget', emoji: '🪑' },
  { id: 'nose-hair-trimmers', text: 'nose hair trimmers', form: 'gadget', emoji: '✂️' },
  { id: 'panic-buttons', text: 'panic buttons', form: 'gadget', emoji: '🔴' },
  { id: 'bug-zappers', text: 'bug zappers', form: 'gadget', emoji: '🪰' },
  { id: 'wood-chippers', text: 'wood chippers', form: 'gadget', emoji: '🪵' },
  { id: 'space-heaters', text: 'space heaters', form: 'gadget', emoji: '♨️' },
  { id: 'pogo-sticks', text: 'pogo sticks', form: 'gadget', emoji: '🦘' },
  { id: 'jukeboxes', text: 'jukeboxes', form: 'gadget', emoji: '📻' },
  { id: 'hearing-aids', text: 'hearing aids', form: 'gadget', emoji: '👂' },
  { id: 'ankle-monitors', text: 'ankle monitors', form: 'gadget', emoji: '⛓️' },
  { id: 'shock-collars', text: 'shock collars', form: 'gadget', emoji: '⚡' },
  { id: 'slot-machines', text: 'slot machines', form: 'gadget', emoji: '🎰' },
  { id: 'security-cameras', text: 'security cameras', form: 'gadget', emoji: '📹' },
  { id: 'pacemakers', text: 'pacemakers', form: 'gadget', emoji: '❤️' },
  { id: 'segways', text: 'Segways', form: 'gadget', emoji: '🛴' },
  // Stuff, more (2026-09-27)
  { id: 'used-socks', text: 'used socks', form: 'goods', emoji: '🧦' },
  { id: 'toe-rings', text: 'toe rings', form: 'goods', emoji: '💍' },
  { id: 'crocs', text: 'Crocs', form: 'goods', emoji: '🐊' },
  { id: 'cargo-shorts', text: 'cargo shorts', form: 'goods', emoji: '🩳' },
  { id: 'ugly-sweaters', text: 'ugly sweaters', form: 'goods', emoji: '🧶' },
  { id: 'mom-jeans', text: 'mom jeans', form: 'goods', emoji: '👖' },
  { id: 'bowling-shoes', text: 'bowling shoes', form: 'goods', emoji: '🎳' },
  { id: 'fake-eyelashes', text: 'fake eyelashes', form: 'goods', emoji: '👁️' },
  { id: 'kidney-stones', text: 'kidney stones', form: 'goods', emoji: '🪨' },
  { id: 'belly-button-lint', text: 'belly button lint', form: 'goods', emoji: '🌀' },
  { id: 'toe-fungus', text: 'toe fungus', form: 'goods', emoji: '🦶' },
  { id: 'used-band-aids', text: 'used Band-Aids', form: 'goods', emoji: '🩹' },
  { id: 'earwax-candles', text: 'earwax candles', form: 'goods', emoji: '🕯️' },
  { id: 'hair-plugs', text: 'hair plugs', form: 'goods', emoji: '💇' },
  { id: 'bath-salts', text: 'bath salts', form: 'goods', emoji: '🧂' },
  { id: 'body-pillows', text: 'body pillows', form: 'goods', emoji: '🛏️' },
  { id: 'fidget-spinners', text: 'fidget spinners', form: 'goods', emoji: '🌪️' },
  { id: 'participation-trophies', text: 'participation trophies', form: 'goods', emoji: '🏆' },
  { id: 'fake-rolexes', text: 'fake Rolexes', form: 'goods', emoji: '⌚' },
  { id: 'mouthguards', text: 'mouthguards', form: 'goods', emoji: '🦷' },
  // Pets, more (2026-09-27)
  { id: 'bats', text: 'bats', form: 'pet', emoji: '🦇' },
  { id: 'rats', text: 'rats', form: 'pet', emoji: '🐀' },
  { id: 'snapping-turtles', text: 'snapping turtles', form: 'pet', emoji: '🐢' },
  { id: 'squirrels', text: 'squirrels', form: 'pet', emoji: '🐿️' },
  { id: 'crows', text: 'crows', form: 'pet', emoji: '🐦‍⬛' },
  { id: 'honey-badgers', text: 'honey badgers', form: 'pet', emoji: '🦡' },
  { id: 'piranhas', text: 'piranhas', form: 'pet', emoji: '🐠' },
  { id: 'bedbugs', text: 'bedbugs', form: 'pet', emoji: '🐛' },
  { id: 'emus', text: 'emus', form: 'pet', emoji: '🐦' },
  { id: 'alpacas', text: 'alpacas', form: 'pet', emoji: '🦙' },
  { id: 'toads', text: 'toads', form: 'pet', emoji: '🐸' },
  { id: 'scorpions', text: 'scorpions', form: 'pet', emoji: '🦂' },
  { id: 'vultures', text: 'vultures', form: 'pet', emoji: '🦅' },
  { id: 'jellyfish', text: 'jellyfish', form: 'pet', emoji: '🪼' },
  { id: 'hermit-crabs', text: 'hermit crabs', form: 'pet', emoji: '🦀' },
  { id: 'chihuahuas', text: 'Chihuahuas', form: 'pet', emoji: '🐕' },
  // Services, more (2026-09-27)
  { id: 'foot-rubs', text: 'foot rubs', form: 'service', emoji: '🦶' },
  { id: 'bail-bonds', text: 'bail bonds', form: 'service', emoji: '💵' },
  { id: 'eulogies', text: 'eulogies', form: 'service', emoji: '⚰️' },
  { id: 'fortune-telling', text: 'fortune telling', form: 'service', emoji: '🔮' },
  { id: 'pep-talks', text: 'pep talks', form: 'service', emoji: '📣' },
  { id: 'apology-letters', text: 'apology letters', form: 'service', emoji: '✉️' },
  { id: 'revenge-plots', text: 'revenge plots', form: 'service', emoji: '🗡️' },
  { id: 'haircuts', text: 'haircuts', form: 'service', emoji: '💈' },
  { id: 'tattoo-removal', text: 'tattoo removal', form: 'service', emoji: '💉' },
  { id: 'repossessions', text: 'repossessions', form: 'service', emoji: '🚗' },
  { id: 'witness-protection', text: 'witness protection', form: 'service', emoji: '🕶️' },
  { id: 'dog-walking', text: 'dog walking', form: 'service', emoji: '🦮' },
  { id: 'pet-funerals', text: 'pet funerals', form: 'service', emoji: '🪦' },
  { id: 'couples-counseling', text: 'couples counseling', form: 'service', emoji: '💑' },
  { id: 'lawn-mowing', text: 'lawn mowing', form: 'service', emoji: '🌱' },
  // Rentals, more (2026-09-27)
  { id: 'getaway-cars', text: 'getaway cars', form: 'rental', emoji: '🏎️' },
  { id: 'bouncers', text: 'bouncers', form: 'rental', emoji: '🚪' },
  { id: 'hype-men', text: 'hype men', form: 'rental', emoji: '🎤' },
  { id: 'snow-plows', text: 'snow plows', form: 'rental', emoji: '🚜' },
  { id: 'party-buses', text: 'party buses', form: 'rental', emoji: '🚌' },
  { id: 'fake-families', text: 'fake families', form: 'rental', emoji: '👨‍👩‍👧' },
  { id: 'crying-babies', text: 'crying babies', form: 'rental', emoji: '😭' },
  { id: 'hot-air-balloons', text: 'hot air balloons', form: 'rental', emoji: '🎈' },
  { id: 'submarines', text: 'submarines', form: 'rental', emoji: '🌊' },
  { id: 'ice-cream-trucks', text: 'ice cream trucks', form: 'rental', emoji: '🍦' },
  { id: 'wrecking-balls', text: 'wrecking balls', form: 'rental', emoji: '🏗️' },
  { id: 'stunt-doubles', text: 'stunt doubles', form: 'rental', emoji: '🎬' },
  // Digital, more (2026-09-27)
  { id: 'sad-playlists', text: 'sad playlists', form: 'digital', emoji: '🎵' },
  { id: 'pop-up-ads', text: 'pop-up ads', form: 'digital', emoji: '🪟' },
  { id: 'phishing-scams', text: 'phishing scams', form: 'digital', emoji: '🎣' },
  { id: 'ringtones', text: 'ringtones', form: 'digital', emoji: '📱' },
  { id: 'group-chats', text: 'group chats', form: 'digital', emoji: '💬' },
  { id: 'reaction-videos', text: 'reaction videos', form: 'digital', emoji: '😱' },
  { id: 'loot-boxes', text: 'loot boxes', form: 'digital', emoji: '📦' },
  { id: 'captchas', text: 'CAPTCHAs', form: 'digital', emoji: '🤖' },
  { id: 'comment-sections', text: 'comment sections', form: 'digital', emoji: '🗯️' },
  { id: 'fan-fiction', text: 'fan fiction', form: 'digital', emoji: '📝' },
  { id: 'tiktok-dances', text: 'TikTok dances', form: 'digital', emoji: '💃' },
  { id: 'webinars', text: 'webinars', form: 'digital', emoji: '💻' },
  { id: 'asmr-videos', text: 'ASMR videos', form: 'digital', emoji: '🎧' },
  { id: 'screensavers', text: 'screensavers', form: 'digital', emoji: '🖥️' },
  // Events, more (2026-09-27)
  { id: 'baby-showers', text: 'baby showers', form: 'event', emoji: '🍼' },
  { id: 'bachelor-parties', text: 'bachelor parties', form: 'event', emoji: '🥳' },
  { id: 'funerals', text: 'funerals', form: 'event', emoji: '⚱️' },
  { id: 'office-parties', text: 'office parties', form: 'event', emoji: '🏢' },
  { id: 'proms', text: 'proms', form: 'event', emoji: '🪩' },
  { id: 'block-parties', text: 'block parties', form: 'event', emoji: '🏘️' },
  { id: 'yard-sales', text: 'yard sales', form: 'event', emoji: '🏷️' },
  { id: 'bingo-nights', text: 'bingo nights', form: 'event', emoji: '🎱' },
  { id: 'renaissance-fairs', text: 'Renaissance fairs', form: 'event', emoji: '🏰' },
  { id: 'polar-plunges', text: 'polar plunges', form: 'event', emoji: '🥶' },
  { id: 'luaus', text: 'luaus', form: 'event', emoji: '🌺' },
  { id: 'slumber-parties', text: 'slumber parties', form: 'event', emoji: '🛌' },
  { id: 'tailgates', text: 'tailgates', form: 'event', emoji: '🏈' },
  { id: 'retirement-parties', text: 'retirement parties', form: 'event', emoji: '🎂' },
  { id: 'pta-meetings', text: 'PTA meetings', form: 'event', emoji: '🏫' }
];

export const MODIFIERS: readonly ModifierWord[] = [
  // Fits anything
  { id: 'haunted', text: 'haunted', emoji: '👻', forms: ALL },
  { id: 'used', text: 'used', emoji: '♻️', forms: ALL },
  { id: 'drunk', text: 'drunk', emoji: '🍺', forms: ALL },
  { id: 'moist', text: 'moist', emoji: '💧', forms: ALL },
  { id: 'satanic', text: 'Satanic', emoji: '😈', forms: ALL },
  { id: 'piss-soaked', text: 'piss-soaked', emoji: '🟡', forms: ALL },
  { id: 'cocaine-laced', text: 'cocaine-laced', emoji: '❄️', forms: ALL },
  { id: 'radioactive', text: 'radioactive', emoji: '☢️', forms: ALL },
  { id: 'expired', text: 'expired', emoji: '🦠', forms: ALL },
  { id: 'bootleg', text: 'bootleg', emoji: '📼', forms: ALL },
  { id: 'counterfeit', text: 'counterfeit', emoji: '🪙', forms: ALL },
  { id: 'prison-made', text: 'prison-made', emoji: '⛓️', forms: ALL },
  { id: 'gluten-free', text: 'gluten-free', emoji: '🌾', forms: ALL },
  { id: 'organic', text: 'certified organic', emoji: '🌿', forms: ALL },
  { id: 'artisanal', text: 'artisanal', emoji: '🧑‍🎨', forms: ALL },
  { id: 'military-grade', text: 'military-grade', emoji: '🎖️', forms: ALL },
  { id: 'fda-unapproved', text: 'FDA-unapproved', emoji: '🙅', forms: ALL },
  { id: 'slightly-illegal', text: 'slightly illegal', emoji: '🚓', forms: ALL },
  { id: 'cursed', text: 'cursed', emoji: '🧿', forms: ALL },
  { id: 'demon-possessed', text: 'demon-possessed', emoji: '👹', forms: ALL },
  { id: 'feral', text: 'feral', emoji: '🐺', forms: ALL },
  { id: 'screaming', text: 'screaming', emoji: '😱', forms: ALL },
  { id: 'sweaty', text: 'sweaty', emoji: '💦', forms: ALL },
  { id: 'crusty', text: 'crusty', emoji: '🥖', forms: ALL },
  { id: 'sticky', text: 'suspiciously sticky', emoji: '🍯', forms: ALL },
  { id: 'lukewarm', text: 'lukewarm', emoji: '🌡️', forms: ALL },
  { id: 'hairy', text: 'extra-hairy', emoji: '🪮', forms: ALL },
  { id: 'stolen', text: 'stolen', emoji: '🦹', forms: ALL },
  { id: 'secondhand', text: 'secondhand', emoji: '🏷️', forms: ALL },
  { id: 'recalled', text: 'recently recalled', emoji: '⚠️', forms: ALL },
  { id: 'flammable', text: 'highly flammable', emoji: '🧯', forms: ALL },
  { id: 'explosive', text: 'mildly explosive', emoji: '💥', forms: ALL },
  { id: 'toxic', text: 'toxic', emoji: '☠️', forms: ALL },
  { id: 'sentient', text: 'sentient', emoji: '🧠', forms: ALL },
  { id: 'depressed', text: 'depressed', emoji: '🌧️', forms: ALL },
  { id: 'clingy', text: 'clingy', emoji: '🥺', forms: ALL },
  { id: 'judgmental', text: 'judgmental', emoji: '🧐', forms: ALL },
  { id: 'passive-aggressive', text: 'passive-aggressive', emoji: '🙂', forms: ALL },
  { id: 'hungover', text: 'hungover', emoji: '🤕', forms: ALL },
  { id: 'canadian', text: 'Canadian', emoji: '🍁', forms: ALL },
  { id: 'florida', text: 'Florida', emoji: '🌴', forms: ALL },
  { id: 'medieval', text: 'medieval', emoji: '⚔️', forms: ALL },
  { id: 'soviet', text: 'Soviet', emoji: '🚜', forms: ALL },
  { id: 'bluetooth', text: 'Bluetooth', emoji: '🛜', forms: ALL },
  { id: 'ai-powered', text: 'AI-powered', emoji: '🤖', forms: ALL },
  { id: 'blockchain', text: 'blockchain', emoji: '⛓️‍💥', forms: ALL },
  { id: 'fart-powered', text: 'fart-powered', emoji: '🌬️', forms: ALL },
  { id: 'nuclear', text: 'nuclear-powered', emoji: '⚛️', forms: ALL },
  { id: 'gold-plated', text: 'gold-plated', emoji: '🥇', forms: ALL },
  { id: 'bedazzled', text: 'bedazzled', emoji: '💎', forms: ALL },
  { id: 'invisible', text: 'invisible', emoji: '🫥', forms: ALL },
  { id: 'giant', text: 'giant', emoji: '🏔️', forms: ALL },
  { id: 'tiny', text: 'tiny', emoji: '🤏', forms: ALL },
  { id: 'vegan', text: 'vegan', emoji: '🥬', forms: ALL },
  { id: 'vintage', text: 'vintage', emoji: '🕰️', forms: ALL },
  { id: 'unlicensed', text: 'unlicensed', emoji: '🚫', forms: ALL },
  { id: 'black-market', text: 'black-market', emoji: '🕳️', forms: ALL },
  { id: 'knockoff', text: 'knockoff', emoji: '🥴', forms: ALL },
  { id: 'luxury', text: 'luxury', emoji: '💰', forms: ALL },
  { id: 'discount', text: 'discount', emoji: '🏷️', forms: ALL },
  { id: 'shit-flavored', text: 'shit-flavored', emoji: '💩', forms: ALL },
  { id: 'ass-scented', text: 'ass-scented', emoji: '🦨', forms: ALL },
  { id: 'your-dads', text: "your dad's", emoji: '👨', forms: ALL },
  { id: 'your-exs', text: "your ex's", emoji: '💔', forms: ALL },
  { id: 'government-issued', text: 'government-issued', emoji: '🏛️', forms: ALL },
  { id: 'mob-owned', text: 'mob-owned', emoji: '🎰', forms: ALL },
  { id: 'clown-operated', text: 'clown-operated', emoji: '🤡', forms: ALL },
  { id: 'raccoon-approved', text: 'raccoon-approved', emoji: '🗑️', forms: ALL },
  { id: 'extreme', text: 'EXTREME', emoji: '🤘', forms: ALL },
  { id: 'rabid', text: 'rabid', emoji: '🫨', forms: ALL },
  { id: 'glow-in-the-dark', text: 'glow-in-the-dark', emoji: '🌟', forms: ALL },
  { id: 'underground', text: 'underground', emoji: '⛏️', forms: ALL },
  // Only where it makes sense
  { id: 'edible', text: 'edible', emoji: '🍴', forms: ['goods', 'gadget', 'pet', 'rental'] },
  { id: 'unflushable', text: 'unflushable', emoji: '🪠', forms: STUFF },
  { id: 'deep-fried', text: 'deep-fried', emoji: '🍟', forms: STUFF },
  { id: 'microwaved', text: 'microwaved', emoji: '📡', forms: STUFF },
  { id: 'inflatable', text: 'inflatable', emoji: '🎈', forms: ['goods', 'gadget', 'pet', 'rental', 'event'] },
  { id: 'venomous', text: 'venomous', emoji: '🐍', forms: [...STUFF, 'rental'] },
  { id: 'drive-thru', text: 'drive-thru', emoji: '🚗', forms: ['service', 'food', 'event', 'rental'] },
  { id: 'twenty-four-hour', text: '24-hour', emoji: '🕛', forms: ['service', 'digital', 'rental', 'event', 'food'] },
  // More twists (2026-09-27)
  { id: 'emotionally-unavailable', text: 'emotionally unavailable', emoji: '💔', forms: ALL },
  { id: 'self-aware', text: 'self-aware', emoji: '🧠', forms: ALL },
  { id: 'unhinged', text: 'unhinged', emoji: '🌀', forms: ALL },
  { id: 'amish', text: 'Amish', emoji: '🎩', forms: ALL },
  { id: 'texas-sized', text: 'Texas-sized', emoji: '🤠', forms: ALL },
  { id: 'tax-deductible', text: 'tax-deductible', emoji: '🧾', forms: ALL },
  { id: 'kid-tested', text: 'kid-tested', emoji: '🧒', forms: ALL },
  { id: 'recession-proof', text: 'recession-proof', emoji: '📉', forms: ALL },
  { id: 'off-brand', text: 'off-brand', emoji: '🏷️', forms: ALL },
  { id: 'emo', text: 'emo', emoji: '🖤', forms: ALL },
  { id: 'jacked', text: 'jacked', emoji: '💪', forms: ALL },
  { id: 'soggy', text: 'soggy', emoji: '🌧️', forms: ALL },
  { id: 'smelly', text: 'smelly', emoji: '🦨', forms: ALL },
  { id: 'bulletproof', text: 'bulletproof', emoji: '🛡️', forms: ALL },
  { id: 'waterproof', text: 'waterproof', emoji: '☔', forms: ALL },
  { id: 'hand-me-down', text: 'hand-me-down', emoji: '👕', forms: ALL },
  { id: 'grandpa-approved', text: 'grandpa-approved', emoji: '👴', forms: ALL },
  { id: 'dollar-store', text: 'dollar-store', emoji: '💵', forms: ALL },
  { id: 'airport', text: 'airport', emoji: '✈️', forms: ALL },
  { id: 'truck-stop', text: 'truck stop', emoji: '🚚', forms: ALL },
  { id: 'russian', text: 'Russian', emoji: '🪆', forms: ALL },
  { id: 'australian', text: 'Australian', emoji: '🦘', forms: ALL },
  { id: 'grease-stained', text: 'grease-stained', emoji: '🍔', forms: ALL },
  { id: 'bargain-bin', text: 'bargain-bin', emoji: '🗑️', forms: ALL },
  { id: 'wi-fi-enabled', text: 'Wi-Fi-enabled', emoji: '📶', forms: ALL },
  { id: 'voice-activated', text: 'voice-activated', emoji: '🗣️', forms: ALL },
  { id: 'zombie', text: 'zombie', emoji: '🧟', forms: ALL },
  { id: 'overpriced', text: 'overpriced', emoji: '💸', forms: ALL },
  { id: 'free-range', text: 'free-range', emoji: '🐔', forms: ALL },
  { id: 'osha-violating', text: 'OSHA-violating', emoji: '🚧', forms: ALL },
  { id: 'nasa-rejected', text: 'NASA-rejected', emoji: '🚀', forms: ALL },
  { id: 'hollywood', text: 'Hollywood', emoji: '🎬', forms: ALL },
  { id: 'reality-tv', text: 'reality TV', emoji: '📺', forms: ALL },
  { id: 'rodent-infested', text: 'rodent-infested', emoji: '🐀', forms: ALL },
  { id: 'moldy', text: 'moldy', emoji: '🦠', forms: ALL },
  { id: 'boneless', text: 'boneless', emoji: '🍗', forms: ALL },
  { id: 'industrial-strength', text: 'industrial-strength', emoji: '🏭', forms: ALL },
  { id: 'extra-spicy', text: 'extra-spicy', emoji: '🌶️', forms: ALL },
  { id: 'lead-painted', text: 'lead-painted', emoji: '🎨', forms: STUFF },
  { id: 'asbestos-lined', text: 'asbestos-lined', emoji: '🏚️', forms: [...STUFF, 'rental'] },
  { id: 'self-driving', text: 'self-driving', emoji: '🚘', forms: ['gadget', 'rental', 'service', 'pet'] },
  { id: 'chainsaw-powered', text: 'chainsaw-powered', emoji: '🪚', forms: ['gadget', 'rental', 'service', 'event'] },
  { id: 'farm-to-table', text: 'farm-to-table', emoji: '🚜', forms: ['food', 'service', 'event', 'pet'] },
  { id: 'all-you-can-eat', text: 'all-you-can-eat', emoji: '🍽️', forms: ['food', 'service', 'event', 'rental', 'pet'] }
];

export const AUDIENCES: readonly AudienceWord[] = [
  { id: 'your-mom', text: 'your mom', emoji: '👩' },
  { id: 'your-dad', text: 'your dad', emoji: '👨' },
  { id: 'your-ex', text: 'your ex', emoji: '💔' },
  { id: 'satan', text: 'Satan', emoji: '😈' },
  { id: 'toddlers', text: 'toddlers', emoji: '👶' },
  { id: 'grandmas', text: 'grandmas', emoji: '👵' },
  { id: 'the-irs', text: 'the IRS', emoji: '🧾' },
  { id: 'cops', text: 'cops', emoji: '👮' },
  { id: 'the-fbi', text: 'the FBI', emoji: '🕵️' },
  { id: 'pirates', text: 'pirates', emoji: '🏴‍☠️' },
  { id: 'clowns', text: 'clowns', emoji: '🤡' },
  { id: 'mimes', text: 'mimes', emoji: '🎭' },
  { id: 'cowboys', text: 'cowboys', emoji: '🤠' },
  { id: 'ninjas', text: 'ninjas', emoji: '🥷' },
  { id: 'zombies', text: 'zombies', emoji: '🧟' },
  { id: 'vampires', text: 'vampires', emoji: '🧛' },
  { id: 'aliens', text: 'aliens', emoji: '👽' },
  { id: 'bigfoot', text: 'Bigfoot', emoji: '🦍' },
  { id: 'santa', text: 'Santa', emoji: '🎅' },
  { id: 'tooth-fairy', text: 'the Tooth Fairy', emoji: '🧚' },
  { id: 'easter-bunny', text: 'the Easter Bunny', emoji: '🐰' },
  { id: 'gym-bros', text: 'gym bros', emoji: '🏋️' },
  { id: 'frat-boys', text: 'frat boys', emoji: '🍺' },
  { id: 'soccer-moms', text: 'soccer moms', emoji: '⚽' },
  { id: 'divorced-dads', text: 'divorced dads', emoji: '🚤' },
  { id: 'karens', text: 'Karens', emoji: '💇‍♀️' },
  { id: 'florida-man', text: 'Florida Man', emoji: '🐊' },
  { id: 'canadians', text: 'Canadians', emoji: '🍁' },
  { id: 'hipsters', text: 'hipsters', emoji: '🧔' },
  { id: 'vegans', text: 'vegans', emoji: '🥕' },
  { id: 'influencers', text: 'influencers', emoji: '🤳' },
  { id: 'gamers', text: 'gamers', emoji: '🎮' },
  { id: 'goths', text: 'goths', emoji: '🖤' },
  { id: 'hippies', text: 'hippies', emoji: '☮️' },
  { id: 'stoners', text: 'stoners', emoji: '🥦' },
  { id: 'drunks', text: 'drunks', emoji: '🥴' },
  { id: 'serial-killers', text: 'serial killers', emoji: '🔪' },
  { id: 'the-mob', text: 'the mob', emoji: '💼' },
  { id: 'cult-leaders', text: 'cult leaders', emoji: '🕯️' },
  { id: 'lawyers', text: 'lawyers', emoji: '⚖️' },
  { id: 'dentists', text: 'dentists', emoji: '🦷' },
  { id: 'your-boss', text: 'your boss', emoji: '👔' },
  { id: 'your-landlord', text: 'your landlord', emoji: '🏠' },
  { id: 'hr', text: 'HR', emoji: '📋' },
  { id: 'interns', text: 'interns', emoji: '☕' },
  { id: 'mall-cops', text: 'mall cops', emoji: '🛒' },
  { id: 'prisoners', text: 'prisoners', emoji: '⛓️' },
  { id: 'cavemen', text: 'cavemen', emoji: '🦴' },
  { id: 'ghosts', text: 'ghosts', emoji: '👻' },
  { id: 'wizards', text: 'wizards', emoji: '🧙' },
  { id: 'robots', text: 'robots', emoji: '🤖' },
  { id: 'dinosaurs', text: 'dinosaurs', emoji: '🦖' },
  { id: 'raccoons', text: 'raccoons', emoji: '🦝' },
  { id: 'seagulls', text: 'seagulls', emoji: '🐦' },
  { id: 'astronauts', text: 'astronauts', emoji: '👩‍🚀' },
  { id: 'time-travelers', text: 'time travelers', emoji: '⏳' },
  { id: 'vikings', text: 'Vikings', emoji: '🪓' },
  { id: 'wrestlers', text: 'wrestlers', emoji: '🤼' },
  { id: 'crypto-bros', text: 'crypto bros', emoji: '📉' },
  { id: 'conspiracy-theorists', text: 'conspiracy theorists', emoji: '🛸' },
  { id: 'flat-earthers', text: 'flat earthers', emoji: '🗺️' },
  { id: 'boomers', text: 'boomers', emoji: '👴' },
  { id: 'gen-z', text: 'Gen Z', emoji: '📱' },
  { id: 'babies', text: 'babies', emoji: '🍼' },
  { id: 'teenagers', text: 'teenagers', emoji: '🛹' },
  { id: 'your-nemesis', text: 'your nemesis', emoji: '😠' },
  { id: 'your-therapist', text: 'your therapist', emoji: '🛋️' },
  { id: 'drunk-uncles', text: 'drunk uncles', emoji: '🥃' },
  { id: 'neighbors', text: 'your weird neighbor', emoji: '🏡' },
  { id: 'mothers-in-law', text: 'mothers-in-law', emoji: '👒' },
  { id: 'stepdads', text: 'stepdads', emoji: '🧢' },
  { id: 'bikers', text: 'bikers', emoji: '🏍️' },
  { id: 'truckers', text: 'truckers', emoji: '🚚' },
  { id: 'bank-robbers', text: 'bank robbers', emoji: '🏦' },
  { id: 'spies', text: 'spies', emoji: '🕶️' },
  { id: 'car-salesmen', text: 'used car salesmen', emoji: '🚙' },
  { id: 'lifeguards', text: 'lifeguards', emoji: '🛟' },
  { id: 'mascots', text: 'mascots', emoji: '🐻' },
  { id: 'magicians', text: 'magicians', emoji: '🎩' },
  { id: 'hoarders', text: 'hoarders', emoji: '📦' },
  { id: 'nerds', text: 'nerds', emoji: '🤓' },
  { id: 'bridezillas', text: 'bridezillas', emoji: '👰' },
  // More (2026-09-27)
  { id: 'your-grandpa', text: 'your grandpa', emoji: '👴' },
  { id: 'the-pope', text: 'the Pope', emoji: '⛪' },
  { id: 'elvis', text: 'Elvis', emoji: '🕺' },
  { id: 'abraham-lincoln', text: 'Abraham Lincoln', emoji: '🎩' },
  { id: 'lumberjacks', text: 'lumberjacks', emoji: '🪓' },
  { id: 'nuns', text: 'nuns', emoji: '🙏' },
  { id: 'monks', text: 'monks', emoji: '🧘' },
  { id: 'mermaids', text: 'mermaids', emoji: '🧜' },
  { id: 'leprechauns', text: 'leprechauns', emoji: '🍀' },
  { id: 'trolls', text: 'trolls', emoji: '🧌' },
  { id: 'goblins', text: 'goblins', emoji: '👺' },
  { id: 'werewolves', text: 'werewolves', emoji: '🐺' },
  { id: 'mummies', text: 'mummies', emoji: '🏺' },
  { id: 'cheerleaders', text: 'cheerleaders', emoji: '📣' },
  { id: 'bodybuilders', text: 'bodybuilders', emoji: '🏋️' },
  { id: 'hall-monitors', text: 'hall monitors', emoji: '🚸' },
  { id: 'substitute-teachers', text: 'substitute teachers', emoji: '🍎' },
  { id: 'lunch-ladies', text: 'lunch ladies', emoji: '🍲' },
  { id: 'mall-santas', text: 'mall Santas', emoji: '🎅' },
  { id: 'uber-drivers', text: 'Uber drivers', emoji: '🚕' },
  { id: 'dmv-workers', text: 'DMV workers', emoji: '🪪' },
  { id: 'telemarketers', text: 'telemarketers', emoji: '📞' },
  { id: 'tech-bros', text: 'tech bros', emoji: '💻' },
  { id: 'life-coaches', text: 'life coaches', emoji: '🗣️' },
  { id: 'yoga-moms', text: 'yoga moms', emoji: '🧘‍♀️' },
  { id: 'podcasters', text: 'podcasters', emoji: '🎙️' },
  { id: 'youtubers', text: 'YouTubers', emoji: '📹' },
  { id: 'drag-queens', text: 'drag queens', emoji: '👑' },
  { id: 'hillbillies', text: 'hillbillies', emoji: '🪕' },
  { id: 'surfers', text: 'surfers', emoji: '🏄' },
  { id: 'skaters', text: 'skaters', emoji: '🛹' },
  { id: 'firefighters', text: 'firefighters', emoji: '🚒' },
  { id: 'plumbers', text: 'plumbers', emoji: '🔧' },
  { id: 'bartenders', text: 'bartenders', emoji: '🍸' },
  { id: 'penguins', text: 'penguins', emoji: '🐧' },
  { id: 'the-sharks', text: 'the sharks', emoji: '🦈' },
  { id: 'kindergartners', text: 'kindergartners', emoji: '🧒' },
  { id: 'your-cousin', text: 'your cousin', emoji: '👦' },
  { id: 'your-roommate', text: 'your roommate', emoji: '🛋️' },
  { id: 'the-neighbors', text: 'the neighbors', emoji: '🏡' },
  { id: 'the-illuminati', text: 'the Illuminati', emoji: '🔺' },
  { id: 'the-cia', text: 'the CIA', emoji: '🕵️' },
  { id: 'russian-hackers', text: 'Russian hackers', emoji: '⌨️' },
  { id: 'celebrity-chefs', text: 'celebrity chefs', emoji: '👨‍🍳' },
  { id: 'tv-psychics', text: 'TV psychics', emoji: '🔮' },
  { id: 'televangelists', text: 'televangelists', emoji: '📺' }
];

export const FEATURES: readonly FeatureWord[] = [
  { id: 'bidet', text: 'with a built-in bidet', emoji: '🚿' },
  { id: 'confetti', text: 'guaranteed to explode into confetti', emoji: '🎊' },
  { id: 'free-kidney', text: 'plus a free kidney', emoji: '🫘' },
  { id: 'self-destruct', text: 'with a self-destruct button', emoji: '🔴' },
  { id: 'lifetime-warranty', text: 'with a lifetime warranty (yours)', emoji: '📜' },
  { id: 'fart-button', text: 'with a fart button', emoji: '💨' },
  { id: 'orphan-tears', text: 'powered by orphan tears', emoji: '😢' },
  { id: 'cocaine-hamster', text: 'powered by a hamster on cocaine', emoji: '🐹' },
  { id: 'fire-chance', text: 'with a 1-in-6 chance of catching fire', emoji: '🔥' },
  { id: 'forever-subscription', text: "with a subscription you can't cancel", emoji: '🔁' },
  { id: 'safety-video', text: 'with a 3-hour safety video', emoji: '📼' },
  { id: 'raccoon-approved', text: 'approved by 9 out of 10 raccoons', emoji: '🦝' },
  { id: 'hidden-camera', text: 'with a hidden camera', emoji: '📷' },
  { id: 'live-snake', text: 'with a live snake inside', emoji: '🐍' },
  { id: 'lie-detector', text: 'with a lie detector that shocks you', emoji: '⚡' },
  { id: 'free-divorce', text: 'plus a free divorce', emoji: '💔' },
  { id: 'disbarred-lawyer', text: 'plus a free lawyer (disbarred)', emoji: '⚖️' },
  { id: 'warning-label', text: 'with a 400-page warning label', emoji: '⚠️' },
  { id: 'bathroom-exclusive', text: 'sold only in gas station bathrooms', emoji: '🚻' },
  { id: 'diarrhea', text: 'with explosive diarrhea as a side effect', emoji: '🧻' },
  { id: 'glowing', text: 'with glow-in-the-dark side effects', emoji: '✨' },
  { id: 'raccoon-puppy', text: "plus a free puppy (it's a raccoon)", emoji: '🐶' },
  { id: 'no-money-back', text: 'with a money-back guarantee (no money back)', emoji: '💸' },
  { id: 'burning-drone', text: 'delivered by drone, usually on fire', emoji: '🚁' },
  { id: 'shot-glass', text: 'with a built-in shot glass', emoji: '🥃' },
  { id: 'free-hangover', text: 'plus a free hangover', emoji: '🤕' },
  { id: 'prison-assembled', text: 'assembled by prisoners', emoji: '🔧' },
  { id: 'tiny-man', text: 'with a tiny screaming man inside', emoji: '😱' },
  { id: 'tetanus-shot', text: 'plus a free tetanus shot', emoji: '💉' },
  { id: 'usb-port', text: 'with a USB port for no reason', emoji: '🔌' },
  { id: 'smuggling-compartment', text: 'with a secret smuggling compartment', emoji: '🕵️' },
  { id: 'dad-cry', text: 'guaranteed to make your dad cry', emoji: '😭' },
  { id: 'ruin-thanksgiving', text: 'guaranteed to ruin Thanksgiving', emoji: '🦃' },
  { id: 'car-alarm', text: 'with a car alarm that never stops', emoji: '🚨' },
  { id: 'blood-waiver', text: 'with a waiver you sign in blood', emoji: '🩸' },
  { id: 'hates-you', text: 'with a personality (it hates you)', emoji: '🙃' },
  { id: 'cheeto-dust', text: 'covered in Cheeto dust', emoji: '🧀' },
  { id: 'pepper-spray', text: 'with built-in pepper spray', emoji: '🌶️' },
  { id: 'wrong-address', text: 'with free delivery to the wrong address', emoji: '📦' },
  { id: 'lawsuit-included', text: 'with a class-action lawsuit included', emoji: '🧑‍⚖️' },
  { id: 'drunk-clown', text: 'delivered by a drunk clown', emoji: '🤡' },
  { id: 'used-coffin', text: 'shipped in a used coffin', emoji: '⚰️' },
  { id: 'cupholders', text: 'with 14 cupholders', emoji: '🥤' },
  { id: 'googly-eyes', text: 'with googly eyes', emoji: '👀' },
  { id: 'training-wheels', text: 'with training wheels', emoji: '🚲' },
  { id: 'mullet', text: 'with a mullet', emoji: '💇‍♂️' },
  { id: 'airbags', text: 'with airbags', emoji: '🎈' },
  { id: 'kill-switch', text: 'with a kill switch', emoji: '🔘' },
  { id: 'laugh-track', text: 'with a laugh track', emoji: '😂' },
  { id: 'theme-song', text: 'with its own theme song', emoji: '🎵' },
  { id: 'sad-trombone', text: 'with a sad trombone sound', emoji: '🎺' },
  { id: 'flamethrower', text: 'with a flamethrower attachment', emoji: '🔥' },
  { id: 'mini-fridge', text: 'with a mini fridge', emoji: '🧊' },
  { id: 'tip-jar', text: 'with a tip jar', emoji: '🫙' },
  { id: 'extra-large', text: 'now in extra large', emoji: '📏' },
  { id: 'more-screaming', text: 'now with more screaming', emoji: '📢' },
  { id: 'satanic-backwards', text: 'with a Satanic message if played backwards', emoji: '🎧' },
  { id: 'wizard-blessed', text: "blessed by a guy who says he's a wizard", emoji: '🧙' },
  { id: 'texts-mom', text: 'with an app that texts your mom', emoji: '📱' },
  { id: 'loyalty-card', text: 'with a loyalty card (10th one is free)', emoji: '💳' },
  { id: 'crime-scene-tape', text: 'wrapped in crime scene tape', emoji: '🚧' },
  { id: 'sidecar', text: 'with a sidecar', emoji: '🛵' },
  // More (2026-09-27)
  { id: 'with-a-built-in-karaoke-mode', text: 'with a built-in karaoke mode', emoji: '🎤' },
  { id: 'with-a-cheese-dispenser', text: 'with a cheese dispenser', emoji: '🧀' },
  { id: 'with-a-built-in-ashtray', text: 'with a built-in ashtray', emoji: '🚬' },
  { id: 'with-a-snooze-button', text: 'with a snooze button', emoji: '😴' },
  { id: 'with-a-tiny-top-hat', text: 'with a tiny top hat', emoji: '🎩' },
  { id: 'with-bluetooth-it-never-connects', text: 'with Bluetooth (it never connects)', emoji: '📶' },
  { id: 'with-a-panic-room', text: 'with a panic room', emoji: '🚪' },
  { id: 'with-a-family-of-mice-living-inside', text: 'with a family of mice living inside', emoji: '🐭' },
  { id: 'with-a-curse-lifted-for-4999', text: 'with a curse (lifted for $49.99)', emoji: '🧿' },
  { id: 'with-realistic-crying-sounds', text: 'with realistic crying sounds', emoji: '😭' },
  { id: 'with-a-smell-you-cant-get-rid-of', text: 'with a smell you can\'t get rid of', emoji: '🦨' },
  { id: 'with-rocket-boosters', text: 'with rocket boosters', emoji: '🚀' },
  { id: 'with-a-cayman-islands-bank-account', text: 'with a Cayman Islands bank account', emoji: '🏝️' },
  { id: 'with-a-restraining-order-attached', text: 'with a restraining order attached', emoji: '📜' },
  { id: 'with-an-ai-that-roasts-you', text: 'with an AI that roasts you', emoji: '🤖' },
  { id: 'with-a-mariachi-band', text: 'with a mariachi band', emoji: '🎺' },
  { id: 'with-a-built-in-fog-machine', text: 'with a built-in fog machine', emoji: '🌫️' },
  { id: 'with-a-lifetime-supply-of-mayonnaise', text: 'with a lifetime supply of mayonnaise', emoji: '🫙' },
  { id: 'plus-a-free-colonoscopy', text: 'plus a free colonoscopy', emoji: '🩺' },
  { id: 'plus-a-free-parrot-that-swears', text: 'plus a free parrot that swears', emoji: '🦜' },
  { id: 'plus-a-free-trip-to-ohio', text: 'plus a free trip to Ohio', emoji: '🚌' },
  { id: 'plus-a-coupon-for-5-off', text: 'plus a coupon for 5% off', emoji: '🎟️' },
  { id: 'plus-a-free-haunting', text: 'plus a free haunting', emoji: '👻' },
  { id: 'plus-a-court-date', text: 'plus a court date', emoji: '⚖️' },
  { id: 'plus-one-free-exorcism', text: 'plus one free exorcism', emoji: '✝️' },
  { id: 'now-with-bees', text: 'now with bees', emoji: '🐝' },
  { id: 'now-with-30-more-asbestos', text: 'now with 30% more asbestos', emoji: '🏚️' },
  { id: 'now-gluten-free-still-has-gluten', text: 'now gluten-free (still has gluten)', emoji: '🌾' },
  { id: 'now-in-camo', text: 'now in camo', emoji: '🪖' },
  { id: 'now-dishwasher-safe-it-isnt', text: 'now dishwasher-safe (it isn\'t)', emoji: '🍽️' },
  { id: 'guaranteed-to-get-you-fired', text: 'guaranteed to get you fired', emoji: '💼' },
  { id: 'guaranteed-to-make-grandma-scream', text: 'guaranteed to make grandma scream', emoji: '👵' },
  { id: 'guaranteed-to-attract-raccoons', text: 'guaranteed to attract raccoons', emoji: '🦝' },
  { id: 'powered-by-pure-spite', text: 'powered by pure spite', emoji: '😤' },
  { id: 'powered-by-gas-station-coffee', text: 'powered by gas station coffee', emoji: '☕' },
  { id: 'powered-by-leaded-gasoline', text: 'powered by leaded gasoline', emoji: '⛽' },
  { id: 'narrated-by-a-disappointed-dad', text: 'narrated by a disappointed dad', emoji: '👨' },
  { id: 'narrated-by-a-guy-named-steve', text: 'narrated by a guy named Steve', emoji: '🎙️' },
  { id: 'delivered-by-pigeon', text: 'delivered by pigeon', emoji: '🕊️' },
  { id: 'shipped-from-a-guys-basement', text: 'shipped from a guy\'s basement', emoji: '📦' },
  { id: 'signed-by-a-stranger-at-a-bus-stop', text: 'signed by a stranger at a bus stop', emoji: '✍️' },
  { id: 'signed-in-crayon', text: 'signed in crayon', emoji: '🖍️' },
  { id: 'approved-by-the-florida-dmv', text: 'approved by the Florida DMV', emoji: '🐊' },
  { id: 'blessed-by-a-mall-psychic', text: 'blessed by a mall psychic', emoji: '🔮' },
  { id: 'sold-out-of-a-van', text: 'sold out of a van', emoji: '🚐' },
  { id: 'sold-by-a-guy-named-big-tony', text: 'sold by a guy named Big Tony', emoji: '🧔' },
  { id: 'assembled-with-zero-instructions', text: 'assembled with zero instructions', emoji: '🔧' },
  { id: 'endorsed-by-a-man-who-lives-in-a-tree', text: 'endorsed by a man who lives in a tree', emoji: '🌳' },
  { id: 'covered-in-glitter', text: 'covered in glitter', emoji: '✨' },
  { id: 'covered-in-mysterious-hair', text: 'covered in mysterious hair', emoji: '🦱' },
  { id: 'wrapped-in-bacon', text: 'wrapped in bacon', emoji: '🥓' },
  { id: 'wrapped-in-a-wet-newspaper', text: 'wrapped in a wet newspaper', emoji: '📰' }
];
