// Card-builder pools: a twist, a product, a who and a feature make
// "Cocaine-laced gas station sushi made by Satan, with a built-in bidet".
// Entries can carry a tone, but every game deals from the whole deck now (GAME_TONE), so the cards leave it out.
// Twists list the product forms they make sense with, so a headline never comes out broken.
import type { ProductForm, Tone } from '../types';

export interface ProductWord {
  id: string;
  /** Plural phrase used in the headline, e.g. "toasters". */
  text: string;
  /** Short plural for tight spots, e.g. "toasters". */
  short: string;
  form: ProductForm;
  emoji: string;
  tone?: Tone;
  /** Word roots for generated business names. */
  roots: readonly string[];
}

export interface ModifierWord {
  id: string;
  /** Goes in front of the product: "haunted toasters". */
  text: string;
  emoji: string;
  forms: readonly ProductForm[];
  tone?: Tone;
  root?: string;
}

export interface AudienceWord {
  id: string;
  /** Goes after the connector: "toasters for pirates", "toasters made by pirates". */
  text: string;
  emoji: string;
  tone?: Tone;
}

export interface FeatureWord {
  id: string;
  /**
   * Goes at the end: "toasters for pirates, with a built-in bidet". Always a "with…", "plus…" or "-ed by…" phrase, never
   * "that explodes", so it reads right after any product, singular or plural (a test checks the first word).
   */
  text: string;
  emoji: string;
  tone?: Tone;
}

export type ConnectorId = 'for' | 'made-by' | 'made-from' | 'tested-on' | 'endorsed-by' | 'banned-by' | 'stolen-from' | 'hated-by';

/** The word that joins the product to its who: "toasters [made from] gym bros". The first is the default. */
export const CONNECTORS: readonly { id: ConnectorId; text: string }[] = [
  { id: 'for', text: 'for' },
  { id: 'made-by', text: 'made by' },
  { id: 'made-from', text: 'made from' },
  { id: 'tested-on', text: 'tested on' },
  { id: 'endorsed-by', text: 'endorsed by' },
  { id: 'banned-by', text: 'banned by' },
  { id: 'stolen-from', text: 'stolen from' },
  { id: 'hated-by', text: 'hated by' }
];

const ALL: readonly ProductForm[] = ['food', 'gadget', 'goods', 'pet', 'service', 'rental', 'digital', 'event'];
const STUFF: readonly ProductForm[] = ['food', 'gadget', 'goods', 'pet'];

// The whole deck is deliberately crude and absurd, South Park style: gross, dark, profane, things that could never
// legally exist. Sexuality and dating jokes are fine; sex itself is not (the content test checks for that).
export const PRODUCTS: readonly ProductWord[] = [
  // Food
  { id: 'gas-station-sushi', text: 'gas station sushi', short: 'sushi', form: 'food', emoji: '🍣', roots: ['Sushi', 'Wasabi'] },
  { id: 'hot-dog-water', text: 'bottled hot dog water', short: 'hot dog water', form: 'food', emoji: '🌭', roots: ['Frank', 'Broth'] },
  { id: 'toenail-chips', text: 'toenail potato chips', short: 'chips', form: 'food', emoji: '🥔', roots: ['Crunch', 'Nail'] },
  { id: 'waffle-house-gum', text: 'gum scraped off a Waffle House floor', short: 'gum', form: 'food', emoji: '🍬', roots: ['Chew', 'Gum'] },
  { id: 'sewer-kombucha', text: 'sewer-water kombucha', short: 'kombucha', form: 'food', emoji: '🍵', roots: ['Sewer', 'Booch'] },
  { id: 'lipo-milkshakes', text: 'milkshakes made from liposuction leftovers', short: 'milkshakes', form: 'food', emoji: '🥤', roots: ['Lipo', 'Shake'] },
  { id: 'roadkill-tacos', text: 'roadkill tacos', short: 'tacos', form: 'food', emoji: '🌮', roots: ['Roadkill', 'Taco'] },
  { id: 'laxative-brownies', text: 'laxative brownies', short: 'brownies', form: 'food', emoji: '🍫', roots: ['Brownie', 'Rumble'] },
  { id: 'street-value-gummies', text: 'gummy bears with a street value', short: 'gummies', form: 'food', emoji: '🧸', roots: ['Gummy', 'Stash'] },
  { id: 'expired-cakes', text: 'cakes that expired in 1987', short: 'cakes', form: 'food', emoji: '🍰', roots: ['Cake', 'Vintage'] },
  { id: 'mayo-smoothies', text: 'mayonnaise smoothies', short: 'smoothies', form: 'food', emoji: '🫙', roots: ['Mayo', 'Slurp'] },
  { id: 'raw-chicken-jerky', text: 'raw chicken jerky', short: 'jerky', form: 'food', emoji: '🍗', roots: ['Cluck', 'Salmonella'] },
  { id: 'dumpster-meal-kits', text: 'dumpster-diving meal kits', short: 'meal kits', form: 'food', emoji: '🗑️', roots: ['Dumpster', 'Kit'] },
  { id: 'ashes-coffee', text: 'coffee pods made from cremated relatives', short: 'coffee pods', form: 'food', emoji: '☕', roots: ['Grandpa', 'Brew'] },
  { id: 'urinal-cake-candy', text: 'urinal cakes rebranded as candy', short: 'candy', form: 'food', emoji: '🍭', roots: ['Urinal', 'Candy'] },
  { id: 'mystery-meat-pops', text: 'mystery meat popsicles', short: 'meat pops', form: 'food', emoji: '🍖', roots: ['Mystery', 'Meat'] },
  { id: 'woods-bone-broth', text: 'bone broth from bones we found in the woods', short: 'bone broth', form: 'food', emoji: '🦴', roots: ['Bone', 'Broth'] },
  { id: 'sweat-lemonade', text: 'lemonade made from gym sweat', short: 'lemonade', form: 'food', emoji: '🍋', roots: ['Sweat', 'Lemon'] },
  { id: 'hair-pasta', text: 'restaurant pasta with the hair already in it', short: 'pasta', form: 'food', emoji: '🍝', roots: ['Hairy', 'Noodle'] },
  // Gadgets
  { id: 'snitch-toasters', text: 'toasters that report you to the police', short: 'toasters', form: 'gadget', emoji: '🍞', roots: ['Toast', 'Snitch'] },
  { id: 'pocket-flamethrowers', text: 'pocket flamethrowers', short: 'flamethrowers', form: 'gadget', emoji: '🔥', roots: ['Blaze', 'Scorch'] },
  { id: 'exploding-phones', text: 'phones that explode when you lie', short: 'phones', form: 'gadget', emoji: '📱', roots: ['Kaboom', 'Phone'] },
  { id: 'nut-punch-alarms', text: 'alarm clocks that punch you in the nuts', short: 'alarm clocks', form: 'gadget', emoji: '⏰', roots: ['Punch', 'Wake'] },
  { id: 'poop-roombas', text: 'robot vacuums that smear dog poop everywhere', short: 'robot vacuums', form: 'gadget', emoji: '🧹', roots: ['Smear', 'Vac'] },
  { id: 'fart-tvs', text: 'smell-o-vision TVs (farts only)', short: 'TVs', form: 'gadget', emoji: '📺', roots: ['Whiff', 'Vision'] },
  { id: 'search-history-printers', text: 'printers that only print your search history', short: 'printers', form: 'gadget', emoji: '🖨️', roots: ['History', 'Print'] },
  { id: 'colonoscopy-cams', text: 'colonoscopy cams that livestream to your family group chat', short: 'butt cams', form: 'gadget', emoji: '📹', roots: ['Colon', 'Stream'] },
  { id: 'kidney-vending', text: 'kidney vending machines', short: 'vending machines', form: 'gadget', emoji: '🏧', roots: ['Kidney', 'Organ'] },
  { id: 'drunk-dial-phones', text: 'phones that drunk-dial your ex every Friday', short: 'phones', form: 'gadget', emoji: '☎️', roots: ['Dial', 'Regret'] },
  { id: 'spy-drones', text: 'drones that spy on your neighbors', short: 'drones', form: 'gadget', emoji: '🚁', roots: ['Snoop', 'Drone'] },
  { id: 'sin-cameras', text: 'cameras that photograph your sins', short: 'cameras', form: 'gadget', emoji: '📷', roots: ['Snap', 'Sin'] },
  { id: 'mind-control-helmets', text: 'mind-control helmets', short: 'helmets', form: 'gadget', emoji: '🧠', roots: ['Brain', 'Obey'] },
  { id: 'taser-pacifiers', text: 'taser pacifiers', short: 'pacifiers', form: 'gadget', emoji: '🍼', roots: ['Zap', 'Binky'] },
  { id: 'gas-extinguishers', text: 'fire extinguishers full of gasoline', short: 'extinguishers', form: 'gadget', emoji: '🧯', roots: ['Whoosh', 'Inferno'] },
  { id: 'toilet-slots', text: 'toilet-mounted slot machines', short: 'toilet slots', form: 'gadget', emoji: '🎰', roots: ['Jackpot', 'Flush'] },
  { id: 'roast-speakers', text: 'smart speakers that roast you in front of guests', short: 'speakers', form: 'gadget', emoji: '🔊', roots: ['Roast', 'Sass'] },
  { id: 'firehose-bidets', text: 'bidets set to fire-hose pressure', short: 'bidets', form: 'gadget', emoji: '🚿', roots: ['Blast', 'Bidet'] },
  { id: 'cheating-calculators', text: 'calculators that cheat on your taxes', short: 'calculators', form: 'gadget', emoji: '🧮', roots: ['Math', 'Loophole'] },
  { id: 'fake-id-printers', text: 'fake ID printers', short: 'printers', form: 'gadget', emoji: '🪪', roots: ['Totally', 'McLovin'] },
  { id: 'nitrous-scooters', text: 'mobility scooters with nitrous', short: 'scooters', form: 'gadget', emoji: '🛵', roots: ['Nitro', 'Scoot'] },
  // Goods
  { id: 'hot-pocket-suppositories', text: 'Hot Pocket suppositories', short: 'suppositories', form: 'goods', emoji: '💊', roots: ['Pocket', 'Rear'] },
  { id: 'dad-fart-candles', text: "scented candles that smell like your dad's farts", short: 'candles', form: 'goods', emoji: '🕯️', roots: ['Dad', 'Toot'] },
  { id: 'sandpaper-tp', text: 'sandpaper toilet paper', short: 'toilet paper', form: 'goods', emoji: '🧻', roots: ['Grit', 'Wipe'] },
  { id: 'earwax-candles', text: 'earwax candles', short: 'candles', form: 'goods', emoji: '👂', roots: ['Wax', 'Earful'] },
  { id: 'tarp-kits', text: 'tarp, shovel and lime starter kits', short: 'starter kits', form: 'goods', emoji: '⛏️', roots: ['Tarp', 'Shovel'] },
  { id: 'used-toothbrushes', text: 'used toothbrushes', short: 'toothbrushes', form: 'goods', emoji: '🪥', roots: ['Brush', 'Bristle'] },
  { id: 'counterfeit-money', text: 'counterfeit money', short: 'fake cash', form: 'goods', emoji: '💵', roots: ['Cash', 'Dollar'] },
  { id: 'haunted-dolls', text: 'secondhand haunted dolls', short: 'dolls', form: 'goods', emoji: '🪆', roots: ['Doll', 'Creepy'] },
  { id: 'jerky-jeans', text: 'jeans made of beef jerky', short: 'jeans', form: 'goods', emoji: '👖', roots: ['Denim', 'Jerky'] },
  { id: 'asbestos-pillows', text: 'asbestos pillows', short: 'pillows', form: 'goods', emoji: '🛏️', roots: ['Fluff', 'Snooze'] },
  { id: 'lead-crayons', text: 'lead paint crayons', short: 'crayons', form: 'goods', emoji: '🖍️', roots: ['Crayon', 'Lead'] },
  { id: 'crime-scene-mattresses', text: 'mattresses from a motel crime scene', short: 'mattresses', form: 'goods', emoji: '🛌', roots: ['Mattress', 'Evidence'] },
  { id: 'cursed-rings', text: 'cursed wedding rings', short: 'rings', form: 'goods', emoji: '💍', roots: ['Ring', 'Doom'] },
  { id: 'shock-leashes', text: 'shock-collar kid leashes', short: 'kid leashes', form: 'goods', emoji: '🦮', roots: ['Leash', 'Zap'] },
  { id: 'chili-diapers', text: 'adult diapers rated for chili night', short: 'diapers', form: 'goods', emoji: '🩲', roots: ['Diaper', 'Chili'] },
  { id: 'urn-toilet-seats', text: 'toilet seats that double as urns', short: 'toilet seats', form: 'goods', emoji: '⚱️', roots: ['Urn', 'Throne'] },
  { id: 'drain-hair-wigs', text: 'wigs made from shower-drain hair', short: 'wigs', form: 'goods', emoji: '💇', roots: ['Drain', 'Wig'] },
  { id: 'stolen-gnomes', text: 'stolen garden gnomes', short: 'gnomes', form: 'goods', emoji: '🍄', roots: ['Gnome', 'Garden'] },
  { id: 'whoopee-cushions', text: 'industrial whoopee cushions', short: 'cushions', form: 'goods', emoji: '💨', roots: ['Toot', 'Squeak'] },
  { id: 'bloodstain-remover', text: 'bloodstain remover (no questions asked)', short: 'stain remover', form: 'goods', emoji: '🧽', roots: ['Scrub', 'Alibi'] },
  { id: 'pool-pee-dye', text: 'dye that shows who peed in the pool', short: 'pee dye', form: 'goods', emoji: '🏊', roots: ['Tinkle', 'Splash'] },
  // Pets
  { id: 'attack-hamsters', text: 'trained attack hamsters', short: 'hamsters', form: 'pet', emoji: '🐹', roots: ['Hammy', 'Fury'] },
  { id: 'raccoon-butlers', text: 'raccoon butlers', short: 'raccoons', form: 'pet', emoji: '🦝', roots: ['Trash', 'Bandit'] },
  { id: 'support-alligators', text: 'emotional support alligators', short: 'alligators', form: 'pet', emoji: '🐊', roots: ['Gator', 'Chomp'] },
  { id: 'crypto-cats', text: 'cats that mine crypto', short: 'cats', form: 'pet', emoji: '🐈', roots: ['Whisker', 'Coin'] },
  { id: 'support-cockroaches', text: 'emotional support cockroaches', short: 'cockroaches', form: 'pet', emoji: '🪳', roots: ['Roach', 'Scuttle'] },
  { id: 'rabid-therapy-dogs', text: 'therapy dogs with rabies', short: 'therapy dogs', form: 'pet', emoji: '🐕', roots: ['Rabid', 'Pup'] },
  { id: 'swearing-parrots', text: 'parrots that swear at your grandma', short: 'parrots', form: 'pet', emoji: '🦜', roots: ['Squawk', 'Potty'] },
  { id: 'smoking-chimps', text: 'chain-smoking chimpanzees', short: 'chimps', form: 'pet', emoji: '🐒', roots: ['Chimp', 'Smokey'] },
  { id: 'gay-penguins', text: 'gay penguin couples who judge your marriage', short: 'penguins', form: 'pet', emoji: '🐧', roots: ['Waddle', 'Tux'] },
  { id: 'cocaine-bears', text: 'bears on cocaine', short: 'bears', form: 'pet', emoji: '🐻', roots: ['Grizzly', 'Snow'] },
  { id: 'meth-rats', text: 'rats that escaped a meth lab', short: 'rats', form: 'pet', emoji: '🐀', roots: ['Rat', 'Tweak'] },
  { id: 'attack-geese', text: 'attack geese', short: 'geese', form: 'pet', emoji: '🦢', roots: ['Honk', 'Goose'] },
  { id: 'pooping-pigeons', text: 'pigeons trained to poop on your enemies', short: 'pigeons', form: 'pet', emoji: '🐦', roots: ['Coo', 'Splat'] },
  { id: 'guard-llamas', text: 'guard llamas that spit on sight', short: 'llamas', form: 'pet', emoji: '🦙', roots: ['Llama', 'Spit'] },
  { id: 'lawyer-goldfish', text: 'goldfish with law degrees', short: 'goldfish', form: 'pet', emoji: '🐠', roots: ['Fin', 'Esquire'] },
  { id: 'depressed-dolphins', text: 'clinically depressed dolphins', short: 'dolphins', form: 'pet', emoji: '🐬', roots: ['Flipper', 'Mope'] },
  { id: 'feral-hogs', text: '30 to 50 feral hogs', short: 'hogs', form: 'pet', emoji: '🐗', roots: ['Hog', 'Stampede'] },
  { id: 'incontinent-ponies', text: 'incontinent ponies', short: 'ponies', form: 'pet', emoji: '🐴', roots: ['Pony', 'Puddle'] },
  { id: 'suited-tarantulas', text: 'tarantulas in tiny suits', short: 'tarantulas', form: 'pet', emoji: '🕷️', roots: ['Spider', 'Dapper'] },
  // Services
  { id: 'backyard-dentistry', text: 'unlicensed backyard dentistry', short: 'dentistry', form: 'service', emoji: '🦷', roots: ['Tooth', 'Drill'] },
  { id: 'poop-mailing', text: 'anonymous poop mailed to your enemies', short: 'poop mail', form: 'service', emoji: '💩', roots: ['Poop', 'Parcel'] },
  { id: 'tax-evasion-lessons', text: 'tax evasion lessons', short: 'lessons', form: 'service', emoji: '📚', roots: ['Loophole', 'Offshore'] },
  { id: 'fake-mourners', text: 'professional fake crying at funerals', short: 'fake crying', form: 'service', emoji: '😭', roots: ['Sob', 'Weep'] },
  { id: 'ransom-notes', text: 'ransom note writing', short: 'ransom notes', form: 'service', emoji: '✉️', roots: ['Ransom', 'Scribble'] },
  { id: 'haunt-your-ex', text: 'haunt-your-ex services', short: 'hauntings', form: 'service', emoji: '⚰️', roots: ['Haunt', 'Spook'] },
  { id: 'drive-thru-colonoscopies', text: 'drive-thru colonoscopies', short: 'colonoscopies', form: 'service', emoji: '🚗', roots: ['Colon', 'DriveThru'] },
  { id: 'drunk-drivers', text: 'designated drunk drivers', short: 'drivers', form: 'service', emoji: '🍺', roots: ['Buzzed', 'Ride'] },
  { id: 'bus-stop-therapy', text: 'therapy from a guy at the bus stop', short: 'therapy', form: 'service', emoji: '🚏', roots: ['Therapy', 'Stop'] },
  { id: 'wedgie-appointments', text: 'wedgies by appointment', short: 'wedgies', form: 'service', emoji: '😣', roots: ['Wedgie', 'Yank'] },
  { id: 'breakup-texts', text: 'breakup text writing', short: 'breakup texts', form: 'service', emoji: '💬', roots: ['Dumped', 'Text'] },
  { id: 'gofundme-scams', text: 'sob-story fundraiser writing', short: 'fundraisers', form: 'service', emoji: '💸', roots: ['Sob', 'Fund'] },
  { id: 'drunk-tattoos', text: 'tattoos by a guy who is hammered', short: 'tattoos', form: 'service', emoji: '🖋️', roots: ['Ink', 'Hammered'] },
  { id: 'discount-exorcisms', text: 'discount exorcisms', short: 'exorcisms', form: 'service', emoji: '😈', roots: ['Exorcist', 'Demon'] },
  { id: 'insult-coaching', text: 'personal insult coaching', short: 'insult coaching', form: 'service', emoji: '🗣️', roots: ['Roast', 'Burn'] },
  { id: 'fake-parents', text: 'fake parents for parent-teacher night', short: 'fake parents', form: 'service', emoji: '🎭', roots: ['Parent', 'Imposter'] },
  { id: 'yelling-hitmen', text: 'discount hitmen who mostly just yell', short: 'hitmen', form: 'service', emoji: '🔫', roots: ['Hit', 'Holler'] },
  { id: 'birthday-kidnappings', text: 'surprise birthday kidnappings', short: 'kidnappings', form: 'service', emoji: '🎁', roots: ['Surprise', 'Grab'] },
  // Rentals
  { id: 'grandma-rentals', text: 'grandma rentals', short: 'grandmas', form: 'rental', emoji: '👵', roots: ['Nana', 'Granny'] },
  { id: 'alibi-rentals', text: 'alibi rentals', short: 'alibis', form: 'rental', emoji: '🕵️', roots: ['Alibi', 'Cover'] },
  { id: 'milk-dads', text: 'rental dads who go out for milk and never come back', short: 'dads', form: 'rental', emoji: '🥛', roots: ['Dad', 'Milk'] },
  { id: 'tank-rentals', text: 'army tank rentals', short: 'tanks', form: 'rental', emoji: '🪖', roots: ['Tank', 'Treads'] },
  { id: 'porta-potty-limos', text: 'porta-potty limousines', short: 'porta-potty limos', form: 'rental', emoji: '🚽', roots: ['Throne', 'Flush'] },
  { id: 'emergency-clowns', text: 'emergency clown rentals', short: 'clowns', form: 'rental', emoji: '🤡', roots: ['Honk', 'Clown'] },
  { id: 'body-doubles', text: 'body double rentals', short: 'body doubles', form: 'rental', emoji: '🥸', roots: ['Double', 'Twin'] },
  { id: 'jail-cell-airbnbs', text: 'jail cell Airbnbs', short: 'jail cells', form: 'rental', emoji: '🔑', roots: ['Cell', 'Slammer'] },
  { id: 'prom-hearses', text: 'hearse rentals for prom', short: 'hearses', form: 'rental', emoji: '🪦', roots: ['Hearse', 'Prom'] },
  { id: 'truck-stop-timeshares', text: 'timeshares in a truck stop bathroom', short: 'timeshares', form: 'rental', emoji: '🚻', roots: ['Stall', 'Share'] },
  { id: 'sabotage-wingmen', text: 'wingmen who ruin it on purpose', short: 'wingmen', form: 'rental', emoji: '🪽', roots: ['Wing', 'Wingman'] },
  { id: 'canada-girlfriends', text: 'fake girlfriends who "live in Canada"', short: 'girlfriends', form: 'rental', emoji: '🍁', roots: ['Maple', 'Totally'] },
  { id: 'wedding-uncles', text: 'drunk uncles to liven up your wedding', short: 'uncles', form: 'rental', emoji: '🥃', roots: ['Uncle', 'Toast'] },
  { id: 'filthy-hot-tubs', text: 'hot tubs nobody has cleaned since 2004', short: 'hot tubs', form: 'rental', emoji: '🛁', roots: ['Bubble', 'Funk'] },
  { id: 'shark-tank-rentals', text: 'actual shark tank rentals', short: 'shark tanks', form: 'rental', emoji: '🦈', roots: ['Chomp', 'Fin'] },
  { id: 'stolen-blimps', text: 'stolen blimp rentals', short: 'blimps', form: 'rental', emoji: '🎈', roots: ['Blimp', 'Float'] },
  { id: 'burning-bounce-houses', text: 'bounce houses that are slightly on fire', short: 'bounce houses', form: 'rental', emoji: '🏰', roots: ['Bounce', 'Blaze'] },
  // Digital
  { id: 'wifi-stealers', text: 'apps that steal wifi passwords', short: 'app', form: 'digital', emoji: '📶', roots: ['Wifi', 'Leech'] },
  { id: 'deepfake-grandma', text: 'apps that deepfake your grandma', short: 'app', form: 'digital', emoji: '📲', roots: ['Fake', 'Nana'] },
  { id: 'pyramid-scheme-apps', text: 'pyramid scheme apps', short: 'app', form: 'digital', emoji: '🔺', roots: ['Pyramid', 'Pharaoh'] },
  { id: 'ghost-tinder', text: 'Tinder for ghosts', short: 'app', form: 'digital', emoji: '💀', roots: ['Ghost', 'Swipe'] },
  { id: 'neighbor-podcasts', text: 'true crime podcasts about your neighbors', short: 'podcast', form: 'digital', emoji: '🎙️', roots: ['Pod', 'Crime'] },
  { id: 'sandwich-nfts', text: 'NFTs of half-eaten sandwiches', short: 'NFTs', form: 'digital', emoji: '🥪', roots: ['Crypto', 'Sandwich'] },
  { id: 'wrong-homework-ai', text: 'AIs that do your homework wrong on purpose', short: 'AI', form: 'digital', emoji: '🤖', roots: ['Brain', 'Oops'] },
  { id: 'divorce-parents-apps', text: 'apps that help kids divorce their parents', short: 'app', form: 'digital', emoji: '📝', roots: ['Divorce', 'Kiddo'] },
  { id: 'poop-rating-apps', text: 'apps that rate your poops', short: 'app', form: 'digital', emoji: '📊', roots: ['Poop', 'Rating'] },
  { id: 'fake-review-bots', text: 'fake review generators', short: 'bots', form: 'digital', emoji: '⭐', roots: ['Review', 'Stars'] },
  { id: 'metaverse-timeshares', text: 'metaverse timeshares', short: 'timeshares', form: 'digital', emoji: '🥽', roots: ['Meta', 'Share'] },
  { id: 'quitter-ai-therapists', text: 'AI therapists that tell you to get over it', short: 'AI', form: 'digital', emoji: '🛋️', roots: ['Therapy', 'Whatever'] },
  { id: 'guilt-trip-apps', text: 'apps that text you guilt trips in your mom\'s voice', short: 'app', form: 'digital', emoji: '📱', roots: ['Guilt', 'Mom'] },
  { id: 'rehab-reality-shows', text: 'reality shows filmed inside rehab', short: 'shows', form: 'digital', emoji: '🎥', roots: ['Rehab', 'Reality'] },
  { id: 'dog-meme-coins', text: 'meme coins named after your dog', short: 'coins', form: 'digital', emoji: '🪙', roots: ['Doge', 'Coin'] },
  { id: 'linkedin-history-apps', text: 'apps that post your browser history to LinkedIn', short: 'app', form: 'digital', emoji: '🔗', roots: ['Linked', 'History'] },
  { id: 'drunk-text-ai', text: 'AIs that drunk-text people for you', short: 'AI', form: 'digital', emoji: '🍷', roots: ['Tipsy', 'Text'] },
  { id: 'kid-raising-tablets', text: 'tablets that raise your kids', short: 'tablets', form: 'digital', emoji: '🧒', roots: ['Screen', 'Nanny'] },
  // Events
  { id: 'toddler-mosh-pits', text: 'toddler mosh pits', short: 'mosh pits', form: 'event', emoji: '🤘', roots: ['Mosh', 'Diaper'] },
  { id: 'funeral-raves', text: 'funeral raves', short: 'raves', form: 'event', emoji: '🪩', roots: ['Rave', 'Wake'] },
  { id: 'hot-sauce-duels', text: 'hot sauce duels to the death', short: 'duels', form: 'event', emoji: '🌶️', roots: ['Blaze', 'Duel'] },
  { id: 'no-exit-escape-rooms', text: 'escape rooms with no exit', short: 'escape rooms', form: 'event', emoji: '🔐', roots: ['Escape', 'Trapped'] },
  { id: 'diarrhea-relays', text: 'diarrhea relay races', short: 'relay races', form: 'event', emoji: '🏃', roots: ['Relay', 'Runs'] },
  { id: 'bear-wrestling', text: 'bear wrestling birthday parties', short: 'parties', form: 'event', emoji: '🐾', roots: ['Bear', 'Grizzly'] },
  { id: 'highway-cart-races', text: 'highway shopping cart races', short: 'cart races', form: 'event', emoji: '🛒', roots: ['Cart', 'Zoom'] },
  { id: 'seance-sleepovers', text: 'séance sleepovers', short: 'sleepovers', form: 'event', emoji: '🔮', roots: ['Seance', 'Candle'] },
  { id: 'monster-truck-weddings', text: 'monster truck weddings', short: 'weddings', form: 'event', emoji: '🛻', roots: ['Truck', 'Crush'] },
  { id: 'divorce-parties', text: 'divorce parties with a piñata of your ex', short: 'divorce parties', form: 'event', emoji: '🪅', roots: ['Pinata', 'Single'] },
  { id: 'explosive-gender-reveals', text: 'gender reveal parties with real explosives', short: 'gender reveals', form: 'event', emoji: '💣', roots: ['Reveal', 'Boom'] },
  { id: 'toddler-bar-crawls', text: 'bar crawls for toddlers', short: 'bar crawls', form: 'event', emoji: '🍻', roots: ['Crawl', 'Sippy'] },
  { id: 'thanksgiving-fight-clubs', text: 'Thanksgiving fight clubs', short: 'fight clubs', form: 'event', emoji: '🦃', roots: ['Turkey', 'Brawl'] },
  { id: 'tax-audit-parties', text: 'tax audit parties', short: 'parties', form: 'event', emoji: '🥳', roots: ['Audit', 'Party'] },
  { id: 'pointless-interventions', text: "surprise interventions for people who don't need one", short: 'interventions', form: 'event', emoji: '🎉', roots: ['Intervention', 'Oops'] },
  { id: 'lawnmower-derbies', text: 'lawnmower demolition derbies', short: 'derbies', form: 'event', emoji: '🚜', roots: ['Mower', 'Crash'] },
  { id: 'sauna-chili-cookoffs', text: 'chili cook-offs in a sauna', short: 'cook-offs', form: 'event', emoji: '🧖', roots: ['Chili', 'Steam'] }
];

export const MODIFIERS: readonly ModifierWord[] = [
  // Fits anything
  { id: 'cocaine-laced', text: 'cocaine-laced', emoji: '❄️', forms: ALL, root: 'Snow' },
  { id: 'piss-soaked', text: 'piss-soaked', emoji: '🟡', forms: ALL, root: 'Piss' },
  { id: 'found-on-a-dead-guy', text: 'found-on-a-dead-guy', emoji: '🪦', forms: ALL, root: 'Corpse' },
  { id: 'meth-lab-made', text: 'made-in-a-meth-lab', emoji: '⚗️', forms: ALL, root: 'Cook' },
  { id: 'mystery-hair', text: 'covered-in-mystery-hair', emoji: '🪮', forms: ALL, root: 'Hairy' },
  { id: 'taco-bell-powered', text: 'Taco Bell-powered', emoji: '🌯', forms: ALL, root: 'Bell' },
  { id: 'hungover', text: 'hungover', emoji: '🤕', forms: ALL, root: 'Hangover' },
  { id: 'blood-soaked', text: 'blood-soaked', emoji: '🩸', forms: ALL, root: 'Bloody' },
  { id: 'walmart-parking-lot', text: 'found-in-a-Walmart-parking-lot', emoji: '🅿️', forms: ALL, root: 'Lot' },
  { id: 'canadian', text: 'Canadian', emoji: '🍁', forms: ALL, root: 'Maple' },
  { id: 'drunk', text: 'drunk', emoji: '🍺', forms: ALL, root: 'Wasted' },
  { id: 'clinically-depressed', text: 'clinically depressed', emoji: '🌧️', forms: ALL, root: 'Mope' },
  { id: 'shit-flavored', text: 'shit-flavored', emoji: '💩', forms: ALL, root: 'Crap' },
  { id: 'ass-scented', text: 'ass-scented', emoji: '🦨', forms: ALL, root: 'Rump' },
  { id: 'damn-near-lethal', text: 'damn-near-lethal', emoji: '☠️', forms: ALL, root: 'Lethal' },
  { id: 'satanic', text: 'Satanic', emoji: '😈', forms: ALL, root: 'Satan' },
  { id: 'prison-made', text: 'prison-made', emoji: '⛓️', forms: ALL, root: 'Cellblock' },
  { id: 'hoarder-owned', text: 'previously-owned-by-a-hoarder', emoji: '📦', forms: ALL, root: 'Hoard' },
  { id: 'crusty', text: 'crusty', emoji: '🥖', forms: ALL, root: 'Crust' },
  { id: 'sweaty', text: 'extra-sweaty', emoji: '💦', forms: ALL, root: 'Swampy' },
  { id: 'some-assembly', text: 'some-assembly-required', emoji: '🔧', forms: ALL, root: 'Assembly' },
  { id: 'lukewarm', text: 'lukewarm', emoji: '🌡️', forms: ALL, root: 'Tepid' },
  { id: 'florida-grown', text: 'Florida-grown', emoji: '🌴', forms: ALL, root: 'Florida' },
  { id: 'ethically-questionable', text: 'ethically questionable', emoji: '🤨', forms: ALL, root: 'Shady' },
  { id: 'cia-approved', text: 'CIA-approved', emoji: '🕶️', forms: ALL, root: 'Classified' },
  { id: 'lightly-used', text: 'lightly used', emoji: '♻️', forms: ALL, root: 'Used' },
  { id: 'drunk-assembled', text: 'drunk-assembled', emoji: '🔩', forms: ALL, root: 'Wobbly' },
  { id: 'dead-dog-possessed', text: 'possessed-by-your-dead-dog', emoji: '🐶', forms: ALL, root: 'Fido' },
  { id: 'toddler-made', text: 'handmade-by-toddlers', emoji: '👶', forms: ALL, root: 'Tot' },
  { id: 'gluten-free-asbestos', text: 'gluten-free (but full of asbestos)', emoji: '🌾', forms: ALL, root: 'Wholesome' },
  { id: 'medically-inadvisable', text: 'medically inadvisable', emoji: '🚑', forms: ALL, root: 'Ambulance' },
  { id: 'court-ordered', text: 'court-ordered', emoji: '👨‍⚖️', forms: ALL, root: 'Probation' },
  { id: 'radioactive', text: 'radioactive', emoji: '☢️', forms: ALL, root: 'Glow' },
  { id: 'fda-unapproved', text: 'FDA-unapproved', emoji: '🙅', forms: ALL, root: 'Unapproved' },
  { id: 'haunted', text: 'haunted', emoji: '👻', forms: ALL, root: 'Spooky' },
  { id: 'slightly-illegal', text: 'slightly illegal', emoji: '🚓', forms: ALL, root: 'Outlaw' },
  { id: 'military-grade', text: 'military-grade', emoji: '🎖️', forms: ALL, root: 'Tactical' },
  { id: 'cursed', text: 'cursed', emoji: '🧿', forms: ALL, root: 'Hex' },
  { id: 'extremely-flammable', text: 'extremely flammable', emoji: '🧯', forms: ALL, root: 'Blaze' },
  { id: 'recently-recalled', text: 'recently recalled', emoji: '⚠️', forms: ALL, root: 'Recall' },
  { id: 'mildly-explosive', text: 'mildly explosive', emoji: '💥', forms: ALL, root: 'Kaboom' },
  { id: 'demon-possessed', text: 'demon-possessed', emoji: '👹', forms: ALL, root: 'Demon' },
  { id: 'definitely-not-stolen', text: 'definitely-not-stolen', emoji: '🦹', forms: ALL, root: 'Swipe' },
  { id: 'screaming', text: 'screaming', emoji: '😱', forms: ALL, root: 'Scream' },
  { id: 'multi-level-marketing', text: 'multi-level-marketing', emoji: '📈', forms: ALL, root: 'Upline' },
  { id: 'banned-in-47-countries', text: 'banned-in-47-countries', emoji: '🌍', forms: ALL, root: 'Banned' },
  { id: 'suspiciously-cheap', text: 'suspiciously cheap', emoji: '🏷️', forms: ALL, root: 'Deal' },
  { id: 'black-market', text: 'black-market', emoji: '🕳️', forms: ALL, root: 'Shady' },
  { id: 'unlicensed', text: 'unlicensed', emoji: '🚫', forms: ALL, root: 'Rogue' },
  { id: 'expired', text: 'expired', emoji: '🦠', forms: ALL, root: 'Moldy' },
  { id: 'feral', text: 'feral', emoji: '🐺', forms: ALL, root: 'Feral' },
  { id: 'moist', text: 'moist', emoji: '💧', forms: ALL, root: 'Damp' },
  { id: 'emotionally-unstable', text: 'emotionally unstable', emoji: '🥲', forms: ALL, root: 'Drama' },
  { id: 'clown-operated', text: 'clown-operated', emoji: '🤡', forms: ALL, root: 'Honk' },
  { id: 'raccoon-certified', text: 'raccoon-certified', emoji: '🗑️', forms: ALL, root: 'Bandit' },
  { id: 'grandma-possessed', text: 'grandma-possessed', emoji: '👵', forms: ALL, root: 'Nana' },
  { id: 'nuclear-powered', text: 'nuclear-powered', emoji: '⚛️', forms: ALL, root: 'Atomic' },
  { id: 'extremely-sticky', text: 'extremely sticky', emoji: '🍯', forms: ALL, root: 'Sticky' },
  { id: 'judgmental', text: 'judgmental', emoji: '🧐', forms: ALL, root: 'Judge' },
  { id: 'wildly-overpriced', text: 'wildly overpriced', emoji: '💰', forms: ALL, root: 'Premium' },
  { id: 'mob-sponsored', text: 'mob-sponsored', emoji: '🎰', forms: ALL, root: 'Family' },
  { id: 'illegal-in-florida', text: 'illegal-in-Florida', emoji: '🐊', forms: ALL, root: 'Florida' },
  { id: 'counterfeit', text: 'counterfeit', emoji: '🪙', forms: ALL, root: 'Knockoff' },
  { id: 'bootleg', text: 'bootleg', emoji: '📼', forms: ALL, root: 'Bootleg' },
  { id: 'unkillable', text: 'unkillable', emoji: '🪳', forms: ALL, root: 'Immortal' },
  { id: 'ai-powered', text: 'AI-powered', emoji: '🤖', forms: ALL, root: 'Bot' },
  { id: 'blockchain', text: 'blockchain-enabled', emoji: '⛓️‍💥', forms: ALL, root: 'Chain' },
  { id: 'influencer-endorsed', text: 'influencer-endorsed', emoji: '🤳', forms: ALL, root: 'Hype' },
  { id: 'foot-scented', text: 'foot-scented', emoji: '🦶', forms: ALL, root: 'Toe' },
  { id: 'fart-powered', text: 'fart-powered', emoji: '🌬️', forms: ALL, root: 'Toot' },
  { id: 'pre-vomited', text: 'pre-vomited', emoji: '🤮', forms: ALL, root: 'Hurl' },
  // Only where it makes sense
  { id: 'edible', text: 'edible', emoji: '🍴', forms: ['goods', 'gadget', 'pet', 'rental'], root: 'Snack' },
  { id: 'unflushable', text: 'unflushable', emoji: '🚽', forms: STUFF, root: 'Clog' },
  { id: 'pre-chewed', text: 'pre-chewed', emoji: '🦷', forms: ['food', 'goods', 'pet'], root: 'Chewy' },
  { id: 'unrefrigerated', text: 'unrefrigerated', emoji: '🧊', forms: ['food', 'goods', 'pet'], root: 'Warm' },
  { id: 'venomous', text: 'venomous', emoji: '🐍', forms: [...STUFF, 'rental'], root: 'Venom' },
  { id: 'rocket-powered', text: 'rocket-powered', emoji: '🚀', forms: ['gadget', 'goods', 'pet', 'rental', 'event'], root: 'Turbo' },
  { id: 'glow-in-the-dark', text: 'glow-in-the-dark', emoji: '🌟', forms: ['food', 'gadget', 'goods', 'pet', 'event'], root: 'Glow' },
  { id: 'underground', text: 'underground', emoji: '⛏️', forms: ['event', 'service', 'rental', 'food'], root: 'Tunnel' },
  { id: 'twenty-four-hour', text: '24-hour', emoji: '🕛', forms: ['service', 'digital', 'rental', 'event', 'food'], root: 'AllNight' }
];

export const AUDIENCES: readonly AudienceWord[] = [
  { id: 'the-irs', text: 'the IRS', emoji: '🧾' },
  { id: 'your-ex', text: 'your ex', emoji: '💔' },
  { id: 'pirates', text: 'pirates', emoji: '🏴‍☠️' },
  { id: 'your-mom', text: 'your mom', emoji: '👩' },
  { id: 'satan', text: 'Satan', emoji: '😈' },
  { id: 'drunk-uncle', text: 'your drunk uncle at Thanksgiving', emoji: '🥃' },
  { id: 'racist-grandpa', text: 'your racist grandpa', emoji: '👴' },
  { id: 'moms-new-boyfriend', text: "your mom's new boyfriend, Gary", emoji: '🧔' },
  { id: 'pool-peers', text: 'people who pee in the pool', emoji: '🏊' },
  { id: 'peaked-chads', text: 'guys named Chad who peaked in high school', emoji: '🏈' },
  { id: 'boat-dads', text: 'divorced dads with a boat', emoji: '🚤' },
  { id: 'tinder-dads', text: 'divorced dads on Tinder', emoji: '📲' },
  { id: 'unwashed-hands', text: "people who don't wash their hands", emoji: '🧼' },
  { id: 'dieting-serial-killers', text: 'serial killers on a diet', emoji: '🔪' },
  { id: 'new-swearers', text: 'kids who just learned to swear', emoji: '🤬' },
  { id: 'urinal-crapper', text: 'the guy who craps in the office urinal', emoji: '🚽' },
  { id: 'rehab-rich-kids', text: 'rich kids in rehab', emoji: '💎' },
  { id: 'smoking-mascots', text: 'theme park mascots on their smoke break', emoji: '🚬' },
  { id: 'manager-askers', text: 'people who ask to speak to the manager', emoji: '💅' },
  { id: 'hungover-bridesmaids', text: 'hungover bridesmaids', emoji: '👰' },
  { id: 'k-repliers', text: 'people who reply "k"', emoji: '💬' },
  { id: 'harley-midlife', text: 'middle-aged men who just bought a motorcycle', emoji: '🏍️' },
  { id: 'elevator-farters', text: 'people who fart in elevators', emoji: '🛗' },
  { id: 'hemorrhoid-sufferers', text: 'people with angry hemorrhoids', emoji: '🍩' },
  { id: 'mlm-moms', text: 'moms running an MLM', emoji: '💄' },
  { id: 'washed-up-child-stars', text: 'washed-up child stars', emoji: '🌟' },
  { id: 'sword-collectors', text: 'grown men who collect swords', emoji: '⚔️' },
  { id: 'well-actually', text: 'guys who say "well, actually"', emoji: '☝️' },
  { id: 'drunk-santas', text: 'drunk mall Santas', emoji: '🎅' },
  { id: 'easter-bunny-cartel', text: "the Easter Bunny's drug cartel", emoji: '🐰' },
  { id: 'canadians', text: 'Canadians', emoji: '🍁' },
  { id: 'microwave-second', text: 'people who leave one second on the microwave', emoji: '⏲️' },
  { id: 'podcast-bros', text: 'podcast bros', emoji: '🎧' },
  { id: 'unshowered-gamers', text: "gamers who haven't showered since launch day", emoji: '🎮' },
  { id: 'live-laugh-love', text: 'people with a "Live Laugh Love" sign', emoji: '🏡' },
  { id: 'lunch-thieves', text: 'coworkers who steal your lunch', emoji: '🥡' },
  { id: 'commitment-vampires', text: 'vampires with commitment issues', emoji: '🧛' },
  { id: 'hoa-presidents', text: 'HOA presidents drunk on power', emoji: '🏘️' },
  { id: 'loud-chewers', text: 'people who chew with their mouth open', emoji: '😬' },
  { id: 'bathroom-phone-talkers', text: 'people who take phone calls on the toilet', emoji: '📞' },
  { id: 'retired-supervillains', text: 'retired supervillains', emoji: '🦹' },
  { id: 'toddlers-with-lawyers', text: 'toddlers with lawyers', emoji: '👶' },
  { id: 'banned-from-costco', text: 'people banned from Costco', emoji: '🛒' },
  { id: 'bigfoot', text: 'Bigfoot', emoji: '🦍' },
  { id: 'mob-debtors', text: 'people who owe the mob money', emoji: '💼' },
  { id: 'florida-men', text: 'Florida Men', emoji: '🐊' },
  { id: 'budget-cult-leaders', text: 'cult leaders on a budget', emoji: '🕯️' },
  { id: 'hr-departments', text: 'HR departments', emoji: '📋' },
  { id: 'gym-bros', text: 'gym bros', emoji: '🏋️' },
  { id: 'canceled-influencers', text: 'canceled influencers', emoji: '🤳' },
  { id: 'escaped-convicts', text: 'escaped convicts', emoji: '⛓️' },
  { id: 'street-racing-grandmas', text: 'grandmas who street race', emoji: '🏎️' },
  { id: 'sleepless-parents', text: 'parents who have not slept since 2019', emoji: '🍼' },
  { id: 'fired-secret-agents', text: 'fired secret agents', emoji: '🕵️' },
  { id: 'lunch-break-robbers', text: 'bank robbers on their lunch break', emoji: '🏦' },
  { id: 'conspiracy-theorists', text: 'conspiracy theorists', emoji: '🛸' },
  { id: 'office-fish-microwavers', text: 'people who microwave fish at work', emoji: '🐟' },
  { id: 'mall-cops', text: 'mall cops', emoji: '👮' },
  { id: 'gassy-grandpas', text: 'gassy grandpas', emoji: '💨' },
  { id: 'fbi-hiders', text: 'people hiding from the FBI', emoji: '🥷' },
  { id: 'broke-crypto-bros', text: 'crypto bros who lost it all', emoji: '📉' },
  { id: 'plane-clappers', text: 'people who clap when the plane lands', emoji: '🛬' },
  { id: 'reply-all-people', text: 'people who hit reply-all', emoji: '📧' },
  { id: 'your-landlord', text: 'your landlord', emoji: '🏠' },
  { id: 'gym-grunters', text: 'the guy at the gym who grunts', emoji: '💪' },
  { id: 'glue-eaters', text: 'kids who eat glue', emoji: '🧴' },
  { id: 'per-my-last-email', text: 'people who say "per my last email"', emoji: '📨' },
  { id: 'flat-earthers', text: 'flat earthers', emoji: '🗺️' },
  { id: 'dads-at-barbecues', text: 'dads at a barbecue', emoji: '🔥' },
  { id: 'rich-babies', text: 'extremely rich babies', emoji: '👑' },
  { id: 'wall-goblins', text: 'the goblins living in your walls', emoji: '👺' },
  { id: 'your-nemesis', text: 'your nemesis', emoji: '😠' },
  { id: 'feral-teens', text: 'feral teenagers', emoji: '🛹' },
  { id: 'last-nerve-teachers', text: 'teachers on their last nerve', emoji: '🍎' },
  { id: 'overconfident-interns', text: 'overconfident interns', emoji: '☕' },
  { id: 'competitive-eaters', text: 'competitive eaters', emoji: '🍔' },
  { id: 'aliens-probing', text: 'aliens who are bad at probing', emoji: '👽' },
  { id: 'jobless-clowns', text: 'clowns who lost their license', emoji: '🤡' },
  { id: 'dead-grandpa', text: "your dead grandpa's ghost", emoji: '👻' },
  { id: 'gas-station-cashiers', text: 'gas station cashiers who have seen things', emoji: '⛽' }
];

export const FEATURES: readonly FeatureWord[] = [
  { id: 'bidet', text: 'with a built-in bidet', emoji: '🚿' },
  { id: 'confetti', text: 'guaranteed to explode into confetti', emoji: '🎊' },
  { id: 'free-kidney', text: 'plus a free kidney', emoji: '🫘' },
  { id: 'self-destruct', text: 'with a self-destruct button', emoji: '🔴' },
  { id: 'disappointed-dad', text: 'narrated by a disappointed dad', emoji: '🎙️' },
  { id: 'drunk-clown', text: 'delivered by a drunk clown', emoji: '🤡' },
  { id: 'used-coffin', text: 'shipped in a used coffin', emoji: '⚰️' },
  { id: 'lifetime-warranty', text: 'with a lifetime warranty (ends when you die)', emoji: '📜' },
  { id: 'fart-button', text: 'with a built-in fart button', emoji: '💨' },
  { id: 'ex-bluetooth', text: "with Bluetooth that only connects to your ex's phone", emoji: '📶' },
  { id: 'orphan-tears', text: 'powered by the tears of orphans', emoji: '😢' },
  { id: 'cocaine-hamster', text: 'powered by a hamster on cocaine', emoji: '🐹' },
  { id: 'fire-chance', text: 'with a 1-in-6 chance of catching fire', emoji: '🔥' },
  { id: 'forever-subscription', text: 'with a subscription you can never cancel', emoji: '🔁' },
  { id: 'free-exorcism', text: 'plus a coupon for a free exorcism', emoji: '😈' },
  { id: 'safety-video', text: 'with a mandatory 3-hour safety video', emoji: '📼' },
  { id: 'parking-lot-signed', text: 'signed by a guy in the Walmart parking lot', emoji: '✍️' },
  { id: 'not-for-humans', text: 'with fine print that says "not for humans"', emoji: '🔍' },
  { id: 'raccoon-approved', text: 'approved by nine out of ten raccoons', emoji: '🦝' },
  { id: 'hidden-camera', text: 'with a hidden camera (for your safety)', emoji: '📷' },
  { id: 'wizard-blessed', text: "blessed by a guy who says he's a wizard", emoji: '🧙' },
  { id: 'live-snake', text: 'with a live snake inside', emoji: '🐍' },
  { id: 'shock-lie-detector', text: 'with a lie detector that shocks you', emoji: '⚡' },
  { id: 'feet-packaging', text: 'with scratch-and-sniff packaging (smells like feet)', emoji: '🦶' },
  { id: 'free-divorce', text: 'plus a free divorce', emoji: '💔' },
  { id: 'disbarred-lawyer', text: 'plus a free lawyer (disbarred)', emoji: '⚖️' },
  { id: 'texts-mom', text: 'with an app that texts your mom every time you use it', emoji: '📱' },
  { id: 'warning-label', text: 'with a 400-page warning label', emoji: '⚠️' },
  { id: 'bathroom-exclusive', text: 'sold only in gas station bathrooms', emoji: '🚻' },
  { id: 'stuck-karaoke', text: 'with a karaoke machine stuck on one song', emoji: '🎤' },
  { id: 'diarrhea-side-effects', text: 'with side effects that include explosive diarrhea', emoji: '🧻' },
  { id: 'glowing-side-effects', text: 'with glow-in-the-dark side effects', emoji: '✨' },
  { id: 'raccoon-puppy', text: "plus a free puppy (it's a raccoon)", emoji: '🐶' },
  { id: 'no-money-back', text: 'with a money-back guarantee (no money back)', emoji: '💸' },
  { id: 'burning-drone', text: 'delivered by drone, usually on fire', emoji: '🚁' },
  { id: 'shot-glass', text: 'with a built-in shot glass', emoji: '🥃' },
  { id: 'free-hangover', text: 'plus a free hangover', emoji: '🤕' },
  { id: 'prison-assembled', text: 'assembled by prisoners on work release', emoji: '🔧' },
  { id: 'disgraced-dentist', text: 'endorsed by a dentist who lost his license', emoji: '🦷' },
  { id: 'car-smell', text: "with a smell you'll never get out of your car", emoji: '🚗' },
  { id: 'tiny-man', text: 'with a tiny screaming man inside', emoji: '😱' },
  { id: 'tetanus-shot', text: 'plus a free tetanus shot', emoji: '💉' },
  { id: 'backwards-message', text: 'with a Satanic message if you play it backwards', emoji: '🎧' },
  { id: 'usb-port', text: 'with a USB port for no reason', emoji: '🔌' },
  { id: 'smuggling-compartment', text: 'with a hidden compartment for smuggling', emoji: '🕵️' },
  { id: 'dad-cry', text: 'guaranteed to make your dad cry', emoji: '😭' },
  { id: 'applebees-ban', text: "guaranteed to get you banned from Applebee's", emoji: '🍽️' },
  { id: 'ruin-thanksgiving', text: 'guaranteed to ruin Thanksgiving', emoji: '🦃' },
  { id: 'haunted-trial', text: 'with a 30-day free trial of being haunted', emoji: '👻' },
  { id: 'car-alarm', text: 'with a car alarm that goes off every 20 minutes', emoji: '🚨' },
  { id: 'colonoscopy-coupon', text: 'plus a coupon for a discount colonoscopy', emoji: '🩺' },
  { id: 'mystery-pedal', text: 'with a foot pedal nobody understands', emoji: '🦿' },
  { id: 'blood-waiver', text: 'with a waiver you sign in blood', emoji: '🩸' },
  { id: 'hates-you', text: 'with a personality (it hates you)', emoji: '🙃' },
  { id: 'cheeto-dust', text: 'covered in Cheeto dust', emoji: '🧀' },
  { id: 'pepper-spray', text: 'with built-in pepper spray', emoji: '🌶️' },
  { id: 'emoji-manual', text: 'with a manual written entirely in emoji', emoji: '📖' },
  { id: 'wrong-address', text: 'with free delivery to the wrong address', emoji: '📦' },
  { id: 'gary-approved', text: "approved by your mom's new boyfriend, Gary", emoji: '🧔' },
  { id: 'extra-moist', text: 'now in "extra moist"', emoji: '💧' },
  { id: 'crime-scene-tape', text: 'wrapped in crime scene tape', emoji: '🚧' },
  { id: 'lawsuit-included', text: 'with a class-action lawsuit included', emoji: '🧑‍⚖️' }
];
